#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 121
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 52
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_package = 1,
  anon_sym_SEMI = 2,
  anon_sym_import = 3,
  anon_sym_DOT = 4,
  anon_sym_function = 5,
  anon_sym_LPAREN = 6,
  anon_sym_COMMA = 7,
  anon_sym_RPAREN = 8,
  anon_sym_LBRACE = 9,
  anon_sym_RBRACE = 10,
  anon_sym_var = 11,
  anon_sym_EQ = 12,
  aux_sym_number_literal_token1 = 13,
  anon_sym_0x = 14,
  aux_sym_number_literal_token2 = 15,
  anon_sym_PLUS = 16,
  anon_sym_DASH = 17,
  anon_sym_STAR = 18,
  anon_sym_SLASH = 19,
  anon_sym_PERCENT = 20,
  sym_identifier = 21,
  sym_string = 22,
  sym_line_comment = 23,
  sym_block_comment = 24,
  sym_source_file = 25,
  sym_header = 26,
  sym_package_declaration = 27,
  sym_import_statement = 28,
  sym_qualified_identifier = 29,
  sym_statement = 30,
  sym_function_declaration = 31,
  sym_parameter_list = 32,
  sym_block = 33,
  sym_variable_declaration = 34,
  sym_variable_declarator_list = 35,
  sym_variable_declarator = 36,
  sym_variable_initializer = 37,
  sym_array_initializer = 38,
  sym_expression_statement = 39,
  sym_expression = 40,
  sym_number_literal = 41,
  sym_binary_expression = 42,
  sym_function_call = 43,
  sym_argument_list = 44,
  aux_sym_source_file_repeat1 = 45,
  aux_sym_source_file_repeat2 = 46,
  aux_sym_header_repeat1 = 47,
  aux_sym_qualified_identifier_repeat1 = 48,
  aux_sym_parameter_list_repeat1 = 49,
  aux_sym_variable_declarator_list_repeat1 = 50,
  aux_sym_array_initializer_repeat1 = 51,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_package] = "package",
  [anon_sym_SEMI] = ";",
  [anon_sym_import] = "import",
  [anon_sym_DOT] = ".",
  [anon_sym_function] = "function",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_var] = "var",
  [anon_sym_EQ] = "=",
  [aux_sym_number_literal_token1] = "number_literal_token1",
  [anon_sym_0x] = "0x",
  [aux_sym_number_literal_token2] = "number_literal_token2",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PERCENT] = "%",
  [sym_identifier] = "identifier",
  [sym_string] = "string",
  [sym_line_comment] = "line_comment",
  [sym_block_comment] = "block_comment",
  [sym_source_file] = "source_file",
  [sym_header] = "header",
  [sym_package_declaration] = "package_declaration",
  [sym_import_statement] = "import_statement",
  [sym_qualified_identifier] = "qualified_identifier",
  [sym_statement] = "statement",
  [sym_function_declaration] = "function_declaration",
  [sym_parameter_list] = "parameter_list",
  [sym_block] = "block",
  [sym_variable_declaration] = "variable_declaration",
  [sym_variable_declarator_list] = "variable_declarator_list",
  [sym_variable_declarator] = "variable_declarator",
  [sym_variable_initializer] = "variable_initializer",
  [sym_array_initializer] = "array_initializer",
  [sym_expression_statement] = "expression_statement",
  [sym_expression] = "expression",
  [sym_number_literal] = "number_literal",
  [sym_binary_expression] = "binary_expression",
  [sym_function_call] = "function_call",
  [sym_argument_list] = "argument_list",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_source_file_repeat2] = "source_file_repeat2",
  [aux_sym_header_repeat1] = "header_repeat1",
  [aux_sym_qualified_identifier_repeat1] = "qualified_identifier_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [aux_sym_variable_declarator_list_repeat1] = "variable_declarator_list_repeat1",
  [aux_sym_array_initializer_repeat1] = "array_initializer_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_package] = anon_sym_package,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_import] = anon_sym_import,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_function] = anon_sym_function,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_var] = anon_sym_var,
  [anon_sym_EQ] = anon_sym_EQ,
  [aux_sym_number_literal_token1] = aux_sym_number_literal_token1,
  [anon_sym_0x] = anon_sym_0x,
  [aux_sym_number_literal_token2] = aux_sym_number_literal_token2,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [sym_identifier] = sym_identifier,
  [sym_string] = sym_string,
  [sym_line_comment] = sym_line_comment,
  [sym_block_comment] = sym_block_comment,
  [sym_source_file] = sym_source_file,
  [sym_header] = sym_header,
  [sym_package_declaration] = sym_package_declaration,
  [sym_import_statement] = sym_import_statement,
  [sym_qualified_identifier] = sym_qualified_identifier,
  [sym_statement] = sym_statement,
  [sym_function_declaration] = sym_function_declaration,
  [sym_parameter_list] = sym_parameter_list,
  [sym_block] = sym_block,
  [sym_variable_declaration] = sym_variable_declaration,
  [sym_variable_declarator_list] = sym_variable_declarator_list,
  [sym_variable_declarator] = sym_variable_declarator,
  [sym_variable_initializer] = sym_variable_initializer,
  [sym_array_initializer] = sym_array_initializer,
  [sym_expression_statement] = sym_expression_statement,
  [sym_expression] = sym_expression,
  [sym_number_literal] = sym_number_literal,
  [sym_binary_expression] = sym_binary_expression,
  [sym_function_call] = sym_function_call,
  [sym_argument_list] = sym_argument_list,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_source_file_repeat2] = aux_sym_source_file_repeat2,
  [aux_sym_header_repeat1] = aux_sym_header_repeat1,
  [aux_sym_qualified_identifier_repeat1] = aux_sym_qualified_identifier_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [aux_sym_variable_declarator_list_repeat1] = aux_sym_variable_declarator_list_repeat1,
  [aux_sym_array_initializer_repeat1] = aux_sym_array_initializer_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_package] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_function] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_var] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_number_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_0x] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_number_literal_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_header] = {
    .visible = true,
    .named = true,
  },
  [sym_package_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_import_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_qualified_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_function_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_declarator_list] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_declarator] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_initializer] = {
    .visible = true,
    .named = true,
  },
  [sym_array_initializer] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_number_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_header_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_qualified_identifier_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_variable_declarator_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_initializer_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 3,
  [17] = 9,
  [18] = 18,
  [19] = 12,
  [20] = 14,
  [21] = 11,
  [22] = 6,
  [23] = 4,
  [24] = 18,
  [25] = 7,
  [26] = 10,
  [27] = 13,
  [28] = 15,
  [29] = 29,
  [30] = 30,
  [31] = 30,
  [32] = 29,
  [33] = 33,
  [34] = 33,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 39,
  [44] = 44,
  [45] = 45,
  [46] = 44,
  [47] = 47,
  [48] = 45,
  [49] = 41,
  [50] = 50,
  [51] = 42,
  [52] = 47,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 54,
  [63] = 60,
  [64] = 64,
  [65] = 65,
  [66] = 56,
  [67] = 61,
  [68] = 58,
  [69] = 57,
  [70] = 64,
  [71] = 65,
  [72] = 59,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 76,
  [78] = 74,
  [79] = 79,
  [80] = 80,
  [81] = 80,
  [82] = 75,
  [83] = 73,
  [84] = 79,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 87,
  [93] = 93,
  [94] = 94,
  [95] = 94,
  [96] = 86,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 102,
  [105] = 103,
  [106] = 106,
  [107] = 107,
  [108] = 99,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 114,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 116,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(13);
      ADVANCE_MAP(
        '"', 2,
        '%', 35,
        '(', 19,
        ')', 21,
        '*', 33,
        '+', 31,
        ',', 20,
        '-', 32,
        '.', 17,
        '/', 34,
        '0', 28,
        ';', 15,
        '=', 25,
        'f', 55,
        'i', 45,
        'p', 36,
        'v', 37,
        '{', 22,
        '}', 23,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == ')') ADVANCE(21);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '0') ADVANCE(28);
      if (lookahead == '{') ADVANCE(22);
      if (lookahead == '}') ADVANCE(23);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(57);
      if (lookahead == '\\') ADVANCE(10);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(58);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(59);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(30);
      END_STATE();
    case 7:
      if (lookahead == '_') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 9:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(30);
      END_STATE();
    case 10:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 11:
      if (eof) ADVANCE(13);
      ADVANCE_MAP(
        '"', 2,
        '%', 35,
        '(', 19,
        ')', 21,
        '*', 33,
        '+', 31,
        ',', 20,
        '-', 32,
        '/', 34,
        '0', 28,
        ';', 15,
        '=', 25,
        'f', 55,
        'v', 37,
        '}', 23,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 12:
      if (eof) ADVANCE(13);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '0') ADVANCE(28);
      if (lookahead == 'f') ADVANCE(55);
      if (lookahead == 'p') ADVANCE(36);
      if (lookahead == 'v') ADVANCE(37);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(12);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_package);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_import);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_function);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_var);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_number_literal_token1);
      if (lookahead == '_') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_number_literal_token1);
      if (lookahead == '_') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_number_literal_token1);
      if (lookahead == 'x') ADVANCE(29);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_0x);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_number_literal_token2);
      if (lookahead == '_') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(58);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'k') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_block_comment);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 12},
  [2] = {.lex_state = 12},
  [3] = {.lex_state = 11},
  [4] = {.lex_state = 11},
  [5] = {.lex_state = 11},
  [6] = {.lex_state = 11},
  [7] = {.lex_state = 11},
  [8] = {.lex_state = 11},
  [9] = {.lex_state = 11},
  [10] = {.lex_state = 11},
  [11] = {.lex_state = 11},
  [12] = {.lex_state = 11},
  [13] = {.lex_state = 11},
  [14] = {.lex_state = 11},
  [15] = {.lex_state = 11},
  [16] = {.lex_state = 11},
  [17] = {.lex_state = 11},
  [18] = {.lex_state = 11},
  [19] = {.lex_state = 11},
  [20] = {.lex_state = 11},
  [21] = {.lex_state = 11},
  [22] = {.lex_state = 11},
  [23] = {.lex_state = 11},
  [24] = {.lex_state = 11},
  [25] = {.lex_state = 11},
  [26] = {.lex_state = 11},
  [27] = {.lex_state = 11},
  [28] = {.lex_state = 11},
  [29] = {.lex_state = 11},
  [30] = {.lex_state = 11},
  [31] = {.lex_state = 11},
  [32] = {.lex_state = 11},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 12},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 11},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 11},
  [44] = {.lex_state = 11},
  [45] = {.lex_state = 11},
  [46] = {.lex_state = 11},
  [47] = {.lex_state = 11},
  [48] = {.lex_state = 11},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 11},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 11},
  [57] = {.lex_state = 11},
  [58] = {.lex_state = 11},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 11},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 11},
  [64] = {.lex_state = 11},
  [65] = {.lex_state = 11},
  [66] = {.lex_state = 11},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 11},
  [69] = {.lex_state = 11},
  [70] = {.lex_state = 11},
  [71] = {.lex_state = 11},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 11},
  [74] = {.lex_state = 11},
  [75] = {.lex_state = 11},
  [76] = {.lex_state = 11},
  [77] = {.lex_state = 11},
  [78] = {.lex_state = 11},
  [79] = {.lex_state = 11},
  [80] = {.lex_state = 11},
  [81] = {.lex_state = 11},
  [82] = {.lex_state = 11},
  [83] = {.lex_state = 11},
  [84] = {.lex_state = 11},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 1},
  [95] = {.lex_state = 1},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 1},
  [101] = {.lex_state = 1},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 1},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 1},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 1},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 1},
  [114] = {.lex_state = 6},
  [115] = {.lex_state = 6},
  [116] = {.lex_state = 1},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 1},
  [120] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_package] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_import] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_function] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_var] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [aux_sym_number_literal_token1] = ACTIONS(1),
    [anon_sym_0x] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(110),
    [sym_header] = STATE(2),
    [sym_package_declaration] = STATE(38),
    [sym_statement] = STATE(5),
    [sym_function_declaration] = STATE(78),
    [sym_variable_declaration] = STATE(78),
    [sym_expression_statement] = STATE(78),
    [sym_expression] = STATE(30),
    [sym_number_literal] = STATE(18),
    [sym_binary_expression] = STATE(18),
    [sym_function_call] = STATE(18),
    [aux_sym_source_file_repeat1] = STATE(2),
    [aux_sym_source_file_repeat2] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_package] = ACTIONS(7),
    [anon_sym_function] = ACTIONS(9),
    [anon_sym_var] = ACTIONS(11),
    [aux_sym_number_literal_token1] = ACTIONS(13),
    [anon_sym_0x] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
    [sym_string] = ACTIONS(19),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 15,
    ACTIONS(7), 1,
      anon_sym_package,
    ACTIONS(9), 1,
      anon_sym_function,
    ACTIONS(11), 1,
      anon_sym_var,
    ACTIONS(13), 1,
      aux_sym_number_literal_token1,
    ACTIONS(15), 1,
      anon_sym_0x,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(19), 1,
      sym_string,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    STATE(30), 1,
      sym_expression,
    STATE(38), 1,
      sym_package_declaration,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(8), 2,
      sym_statement,
      aux_sym_source_file_repeat2,
    STATE(36), 2,
      sym_header,
      aux_sym_source_file_repeat1,
    STATE(18), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
    STATE(78), 3,
      sym_function_declaration,
      sym_variable_declaration,
      sym_expression_statement,
  [53] = 5,
    ACTIONS(27), 1,
      anon_sym_LPAREN,
    STATE(7), 1,
      sym_argument_list,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(25), 5,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(23), 11,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      sym_string,
  [84] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(31), 5,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(29), 11,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      sym_string,
  [109] = 12,
    ACTIONS(9), 1,
      anon_sym_function,
    ACTIONS(11), 1,
      anon_sym_var,
    ACTIONS(13), 1,
      aux_sym_number_literal_token1,
    ACTIONS(15), 1,
      anon_sym_0x,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(19), 1,
      sym_string,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    STATE(30), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(9), 2,
      sym_statement,
      aux_sym_source_file_repeat2,
    STATE(18), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
    STATE(78), 3,
      sym_function_declaration,
      sym_variable_declaration,
      sym_expression_statement,
  [152] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(35), 5,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(33), 11,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      sym_string,
  [177] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(39), 5,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(37), 11,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      sym_string,
  [202] = 12,
    ACTIONS(9), 1,
      anon_sym_function,
    ACTIONS(11), 1,
      anon_sym_var,
    ACTIONS(13), 1,
      aux_sym_number_literal_token1,
    ACTIONS(15), 1,
      anon_sym_0x,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(19), 1,
      sym_string,
    ACTIONS(41), 1,
      ts_builtin_sym_end,
    STATE(30), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(9), 2,
      sym_statement,
      aux_sym_source_file_repeat2,
    STATE(18), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
    STATE(78), 3,
      sym_function_declaration,
      sym_variable_declaration,
      sym_expression_statement,
  [245] = 12,
    ACTIONS(43), 1,
      ts_builtin_sym_end,
    ACTIONS(45), 1,
      anon_sym_function,
    ACTIONS(48), 1,
      anon_sym_var,
    ACTIONS(51), 1,
      aux_sym_number_literal_token1,
    ACTIONS(54), 1,
      anon_sym_0x,
    ACTIONS(57), 1,
      sym_identifier,
    ACTIONS(60), 1,
      sym_string,
    STATE(30), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(9), 2,
      sym_statement,
      aux_sym_source_file_repeat2,
    STATE(18), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
    STATE(78), 3,
      sym_function_declaration,
      sym_variable_declaration,
      sym_expression_statement,
  [288] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(65), 5,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(63), 11,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      sym_string,
  [313] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(69), 5,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(67), 11,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      sym_string,
  [338] = 12,
    ACTIONS(71), 1,
      anon_sym_function,
    ACTIONS(73), 1,
      anon_sym_RBRACE,
    ACTIONS(75), 1,
      anon_sym_var,
    ACTIONS(77), 1,
      aux_sym_number_literal_token1,
    ACTIONS(79), 1,
      anon_sym_0x,
    ACTIONS(81), 1,
      sym_identifier,
    ACTIONS(83), 1,
      sym_string,
    STATE(31), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(14), 2,
      sym_statement,
      aux_sym_source_file_repeat2,
    STATE(24), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
    STATE(74), 3,
      sym_function_declaration,
      sym_variable_declaration,
      sym_expression_statement,
  [381] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(87), 5,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(85), 11,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      sym_string,
  [406] = 12,
    ACTIONS(71), 1,
      anon_sym_function,
    ACTIONS(75), 1,
      anon_sym_var,
    ACTIONS(77), 1,
      aux_sym_number_literal_token1,
    ACTIONS(79), 1,
      anon_sym_0x,
    ACTIONS(81), 1,
      sym_identifier,
    ACTIONS(83), 1,
      sym_string,
    ACTIONS(89), 1,
      anon_sym_RBRACE,
    STATE(31), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(17), 2,
      sym_statement,
      aux_sym_source_file_repeat2,
    STATE(24), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
    STATE(74), 3,
      sym_function_declaration,
      sym_variable_declaration,
      sym_expression_statement,
  [449] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(93), 5,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(91), 11,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      sym_string,
  [474] = 5,
    ACTIONS(95), 1,
      anon_sym_LPAREN,
    STATE(25), 1,
      sym_argument_list,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(25), 5,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(23), 9,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      sym_string,
  [503] = 12,
    ACTIONS(43), 1,
      anon_sym_RBRACE,
    ACTIONS(97), 1,
      anon_sym_function,
    ACTIONS(100), 1,
      anon_sym_var,
    ACTIONS(103), 1,
      aux_sym_number_literal_token1,
    ACTIONS(106), 1,
      anon_sym_0x,
    ACTIONS(109), 1,
      sym_identifier,
    ACTIONS(112), 1,
      sym_string,
    STATE(31), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(17), 2,
      sym_statement,
      aux_sym_source_file_repeat2,
    STATE(24), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
    STATE(74), 3,
      sym_function_declaration,
      sym_variable_declaration,
      sym_expression_statement,
  [546] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(25), 5,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(23), 11,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      sym_string,
  [571] = 12,
    ACTIONS(71), 1,
      anon_sym_function,
    ACTIONS(75), 1,
      anon_sym_var,
    ACTIONS(77), 1,
      aux_sym_number_literal_token1,
    ACTIONS(79), 1,
      anon_sym_0x,
    ACTIONS(81), 1,
      sym_identifier,
    ACTIONS(83), 1,
      sym_string,
    ACTIONS(115), 1,
      anon_sym_RBRACE,
    STATE(31), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(20), 2,
      sym_statement,
      aux_sym_source_file_repeat2,
    STATE(24), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
    STATE(74), 3,
      sym_function_declaration,
      sym_variable_declaration,
      sym_expression_statement,
  [614] = 12,
    ACTIONS(71), 1,
      anon_sym_function,
    ACTIONS(75), 1,
      anon_sym_var,
    ACTIONS(77), 1,
      aux_sym_number_literal_token1,
    ACTIONS(79), 1,
      anon_sym_0x,
    ACTIONS(81), 1,
      sym_identifier,
    ACTIONS(83), 1,
      sym_string,
    ACTIONS(117), 1,
      anon_sym_RBRACE,
    STATE(31), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(17), 2,
      sym_statement,
      aux_sym_source_file_repeat2,
    STATE(24), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
    STATE(74), 3,
      sym_function_declaration,
      sym_variable_declaration,
      sym_expression_statement,
  [657] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(69), 5,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(67), 9,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      sym_string,
  [680] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(35), 5,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(33), 9,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      sym_string,
  [703] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(31), 5,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(29), 9,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      sym_string,
  [726] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(25), 5,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(23), 9,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      sym_string,
  [749] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(39), 5,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(37), 9,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      sym_string,
  [772] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(65), 5,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(63), 9,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      sym_string,
  [795] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(87), 5,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(85), 9,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      sym_string,
  [818] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(93), 5,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      sym_identifier,
    ACTIONS(91), 9,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      sym_string,
  [841] = 5,
    ACTIONS(125), 1,
      anon_sym_SLASH,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(119), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
    ACTIONS(121), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
    ACTIONS(123), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [867] = 6,
    ACTIONS(129), 1,
      anon_sym_SEMI,
    ACTIONS(135), 1,
      anon_sym_SLASH,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(127), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    ACTIONS(131), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
    ACTIONS(133), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [895] = 6,
    ACTIONS(125), 1,
      anon_sym_SLASH,
    ACTIONS(137), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(127), 3,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
    ACTIONS(123), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(131), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [923] = 5,
    ACTIONS(135), 1,
      anon_sym_SLASH,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(119), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
    ACTIONS(121), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_0x,
      sym_string,
    ACTIONS(133), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [949] = 10,
    ACTIONS(13), 1,
      aux_sym_number_literal_token1,
    ACTIONS(15), 1,
      anon_sym_0x,
    ACTIONS(19), 1,
      sym_string,
    ACTIONS(139), 1,
      anon_sym_LBRACE,
    ACTIONS(141), 1,
      sym_identifier,
    STATE(32), 1,
      sym_expression,
    STATE(70), 1,
      sym_variable_initializer,
    STATE(71), 1,
      sym_array_initializer,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(18), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
  [983] = 10,
    ACTIONS(77), 1,
      aux_sym_number_literal_token1,
    ACTIONS(79), 1,
      anon_sym_0x,
    ACTIONS(83), 1,
      sym_string,
    ACTIONS(143), 1,
      anon_sym_LBRACE,
    ACTIONS(145), 1,
      sym_identifier,
    STATE(29), 1,
      sym_expression,
    STATE(64), 1,
      sym_variable_initializer,
    STATE(65), 1,
      sym_array_initializer,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(24), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
  [1017] = 5,
    ACTIONS(151), 1,
      anon_sym_import,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(37), 2,
      sym_import_statement,
      aux_sym_header_repeat1,
    ACTIONS(147), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    ACTIONS(149), 5,
      anon_sym_package,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1041] = 6,
    ACTIONS(155), 1,
      anon_sym_package,
    STATE(38), 1,
      sym_package_declaration,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(36), 2,
      sym_header,
      aux_sym_source_file_repeat1,
    ACTIONS(153), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    ACTIONS(158), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1067] = 5,
    ACTIONS(164), 1,
      anon_sym_import,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(37), 2,
      sym_import_statement,
      aux_sym_header_repeat1,
    ACTIONS(160), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    ACTIONS(162), 5,
      anon_sym_package,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1091] = 5,
    ACTIONS(151), 1,
      anon_sym_import,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(35), 2,
      sym_import_statement,
      aux_sym_header_repeat1,
    ACTIONS(167), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    ACTIONS(169), 5,
      anon_sym_package,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1115] = 5,
    ACTIONS(173), 1,
      anon_sym_COMMA,
    STATE(46), 1,
      aux_sym_variable_declarator_list_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(175), 3,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
    ACTIONS(171), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1137] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(177), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    ACTIONS(179), 6,
      anon_sym_package,
      anon_sym_import,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1155] = 8,
    ACTIONS(13), 1,
      aux_sym_number_literal_token1,
    ACTIONS(15), 1,
      anon_sym_0x,
    ACTIONS(19), 1,
      sym_string,
    ACTIONS(141), 1,
      sym_identifier,
    ACTIONS(181), 1,
      anon_sym_RPAREN,
    STATE(61), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(18), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
  [1183] = 8,
    ACTIONS(13), 1,
      aux_sym_number_literal_token1,
    ACTIONS(15), 1,
      anon_sym_0x,
    ACTIONS(19), 1,
      sym_string,
    ACTIONS(141), 1,
      sym_identifier,
    ACTIONS(183), 1,
      anon_sym_RBRACE,
    STATE(59), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(18), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
  [1211] = 5,
    ACTIONS(185), 1,
      anon_sym_COMMA,
    STATE(44), 1,
      aux_sym_variable_declarator_list_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(175), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    ACTIONS(171), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1233] = 5,
    ACTIONS(191), 1,
      anon_sym_COMMA,
    STATE(44), 1,
      aux_sym_variable_declarator_list_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(187), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    ACTIONS(189), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1255] = 5,
    ACTIONS(185), 1,
      anon_sym_COMMA,
    STATE(43), 1,
      aux_sym_variable_declarator_list_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(194), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    ACTIONS(196), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1277] = 5,
    ACTIONS(198), 1,
      anon_sym_COMMA,
    STATE(46), 1,
      aux_sym_variable_declarator_list_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(187), 3,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
    ACTIONS(189), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1299] = 4,
    ACTIONS(205), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(201), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
    ACTIONS(203), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
  [1319] = 5,
    ACTIONS(173), 1,
      anon_sym_COMMA,
    STATE(39), 1,
      aux_sym_variable_declarator_list_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(194), 3,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
    ACTIONS(196), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1341] = 8,
    ACTIONS(13), 1,
      aux_sym_number_literal_token1,
    ACTIONS(15), 1,
      anon_sym_0x,
    ACTIONS(19), 1,
      sym_string,
    ACTIONS(141), 1,
      sym_identifier,
    ACTIONS(207), 1,
      anon_sym_RPAREN,
    STATE(67), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(18), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
  [1369] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(209), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    ACTIONS(211), 6,
      anon_sym_package,
      anon_sym_import,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1387] = 8,
    ACTIONS(13), 1,
      aux_sym_number_literal_token1,
    ACTIONS(15), 1,
      anon_sym_0x,
    ACTIONS(19), 1,
      sym_string,
    ACTIONS(141), 1,
      sym_identifier,
    ACTIONS(213), 1,
      anon_sym_RBRACE,
    STATE(72), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(18), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
  [1415] = 4,
    ACTIONS(215), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(201), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
    ACTIONS(203), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_0x,
      sym_string,
  [1435] = 4,
    ACTIONS(135), 1,
      anon_sym_SLASH,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(217), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
    ACTIONS(133), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [1454] = 7,
    ACTIONS(13), 1,
      aux_sym_number_literal_token1,
    ACTIONS(15), 1,
      anon_sym_0x,
    ACTIONS(19), 1,
      sym_string,
    ACTIONS(141), 1,
      sym_identifier,
    STATE(11), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(18), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
  [1479] = 7,
    ACTIONS(13), 1,
      aux_sym_number_literal_token1,
    ACTIONS(15), 1,
      anon_sym_0x,
    ACTIONS(19), 1,
      sym_string,
    ACTIONS(141), 1,
      sym_identifier,
    STATE(53), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(18), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
  [1504] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(187), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_0x,
      sym_string,
    ACTIONS(189), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1521] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(219), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_0x,
      sym_string,
    ACTIONS(221), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1538] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(223), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_0x,
      sym_string,
    ACTIONS(225), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1555] = 6,
    ACTIONS(135), 1,
      anon_sym_SLASH,
    ACTIONS(227), 1,
      anon_sym_COMMA,
    ACTIONS(229), 1,
      anon_sym_RBRACE,
    STATE(92), 1,
      aux_sym_array_initializer_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(133), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [1578] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(231), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_0x,
      sym_string,
    ACTIONS(233), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1595] = 6,
    ACTIONS(135), 1,
      anon_sym_SLASH,
    ACTIONS(227), 1,
      anon_sym_COMMA,
    ACTIONS(235), 1,
      anon_sym_RPAREN,
    STATE(86), 1,
      aux_sym_array_initializer_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(133), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [1618] = 7,
    ACTIONS(77), 1,
      aux_sym_number_literal_token1,
    ACTIONS(79), 1,
      anon_sym_0x,
    ACTIONS(83), 1,
      sym_string,
    ACTIONS(145), 1,
      sym_identifier,
    STATE(21), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(24), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
  [1643] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(231), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
    ACTIONS(233), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1660] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(237), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
    ACTIONS(239), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
  [1677] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(119), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
    ACTIONS(121), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
  [1694] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(187), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
    ACTIONS(189), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1711] = 6,
    ACTIONS(135), 1,
      anon_sym_SLASH,
    ACTIONS(227), 1,
      anon_sym_COMMA,
    ACTIONS(241), 1,
      anon_sym_RPAREN,
    STATE(96), 1,
      aux_sym_array_initializer_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(133), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [1734] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(223), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
    ACTIONS(225), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1751] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(219), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
    ACTIONS(221), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1768] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(237), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
    ACTIONS(239), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_0x,
      sym_string,
  [1785] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(119), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
    ACTIONS(121), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_0x,
      sym_string,
  [1802] = 6,
    ACTIONS(135), 1,
      anon_sym_SLASH,
    ACTIONS(227), 1,
      anon_sym_COMMA,
    ACTIONS(243), 1,
      anon_sym_RBRACE,
    STATE(87), 1,
      aux_sym_array_initializer_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(133), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
  [1825] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(245), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    ACTIONS(247), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1841] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(251), 3,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
    ACTIONS(249), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1857] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(253), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    ACTIONS(255), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1873] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(259), 3,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
    ACTIONS(257), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1889] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(259), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    ACTIONS(257), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1905] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(251), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    ACTIONS(249), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1921] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(263), 3,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
    ACTIONS(261), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1937] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(265), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    ACTIONS(267), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1953] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(265), 3,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
    ACTIONS(267), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1969] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(253), 3,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
    ACTIONS(255), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1985] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(245), 3,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
    ACTIONS(247), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [2001] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(263), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    ACTIONS(261), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [2017] = 4,
    ACTIONS(269), 1,
      anon_sym_COMMA,
    STATE(85), 1,
      aux_sym_array_initializer_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(217), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [2032] = 4,
    ACTIONS(227), 1,
      anon_sym_COMMA,
    ACTIONS(272), 1,
      anon_sym_RPAREN,
    STATE(85), 1,
      aux_sym_array_initializer_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2046] = 4,
    ACTIONS(227), 1,
      anon_sym_COMMA,
    ACTIONS(274), 1,
      anon_sym_RBRACE,
    STATE(85), 1,
      aux_sym_array_initializer_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2060] = 4,
    ACTIONS(276), 1,
      anon_sym_SEMI,
    ACTIONS(278), 1,
      anon_sym_DOT,
    STATE(88), 1,
      aux_sym_qualified_identifier_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2074] = 4,
    ACTIONS(281), 1,
      anon_sym_COMMA,
    ACTIONS(284), 1,
      anon_sym_RPAREN,
    STATE(89), 1,
      aux_sym_parameter_list_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2088] = 4,
    ACTIONS(286), 1,
      anon_sym_COMMA,
    ACTIONS(288), 1,
      anon_sym_RPAREN,
    STATE(89), 1,
      aux_sym_parameter_list_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2102] = 4,
    ACTIONS(290), 1,
      anon_sym_SEMI,
    ACTIONS(292), 1,
      anon_sym_DOT,
    STATE(97), 1,
      aux_sym_qualified_identifier_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2116] = 4,
    ACTIONS(227), 1,
      anon_sym_COMMA,
    ACTIONS(294), 1,
      anon_sym_RBRACE,
    STATE(85), 1,
      aux_sym_array_initializer_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2130] = 4,
    ACTIONS(286), 1,
      anon_sym_COMMA,
    ACTIONS(296), 1,
      anon_sym_RPAREN,
    STATE(90), 1,
      aux_sym_parameter_list_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2144] = 4,
    ACTIONS(298), 1,
      sym_identifier,
    STATE(48), 1,
      sym_variable_declarator,
    STATE(76), 1,
      sym_variable_declarator_list,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2158] = 4,
    ACTIONS(300), 1,
      sym_identifier,
    STATE(45), 1,
      sym_variable_declarator,
    STATE(77), 1,
      sym_variable_declarator_list,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2172] = 4,
    ACTIONS(227), 1,
      anon_sym_COMMA,
    ACTIONS(302), 1,
      anon_sym_RPAREN,
    STATE(85), 1,
      aux_sym_array_initializer_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2186] = 4,
    ACTIONS(292), 1,
      anon_sym_DOT,
    ACTIONS(304), 1,
      anon_sym_SEMI,
    STATE(88), 1,
      aux_sym_qualified_identifier_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2200] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(284), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2209] = 3,
    ACTIONS(306), 1,
      anon_sym_LPAREN,
    STATE(102), 1,
      sym_parameter_list,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2220] = 3,
    ACTIONS(308), 1,
      anon_sym_RPAREN,
    ACTIONS(310), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2231] = 3,
    ACTIONS(312), 1,
      sym_identifier,
    STATE(109), 1,
      sym_qualified_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2242] = 3,
    ACTIONS(314), 1,
      anon_sym_LBRACE,
    STATE(80), 1,
      sym_block,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2253] = 3,
    ACTIONS(298), 1,
      sym_identifier,
    STATE(66), 1,
      sym_variable_declarator,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2264] = 3,
    ACTIONS(316), 1,
      anon_sym_LBRACE,
    STATE(81), 1,
      sym_block,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2275] = 3,
    ACTIONS(300), 1,
      sym_identifier,
    STATE(56), 1,
      sym_variable_declarator,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2286] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(276), 2,
      anon_sym_SEMI,
      anon_sym_DOT,
  [2295] = 3,
    ACTIONS(312), 1,
      sym_identifier,
    STATE(112), 1,
      sym_qualified_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2306] = 3,
    ACTIONS(306), 1,
      anon_sym_LPAREN,
    STATE(104), 1,
      sym_parameter_list,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2317] = 2,
    ACTIONS(318), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2325] = 2,
    ACTIONS(320), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2333] = 2,
    ACTIONS(322), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2341] = 2,
    ACTIONS(324), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2349] = 2,
    ACTIONS(326), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2357] = 2,
    ACTIONS(328), 1,
      aux_sym_number_literal_token2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2365] = 2,
    ACTIONS(330), 1,
      aux_sym_number_literal_token2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2373] = 2,
    ACTIONS(332), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2381] = 2,
    ACTIONS(334), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2389] = 2,
    ACTIONS(336), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2397] = 2,
    ACTIONS(338), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2405] = 2,
    ACTIONS(340), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 53,
  [SMALL_STATE(4)] = 84,
  [SMALL_STATE(5)] = 109,
  [SMALL_STATE(6)] = 152,
  [SMALL_STATE(7)] = 177,
  [SMALL_STATE(8)] = 202,
  [SMALL_STATE(9)] = 245,
  [SMALL_STATE(10)] = 288,
  [SMALL_STATE(11)] = 313,
  [SMALL_STATE(12)] = 338,
  [SMALL_STATE(13)] = 381,
  [SMALL_STATE(14)] = 406,
  [SMALL_STATE(15)] = 449,
  [SMALL_STATE(16)] = 474,
  [SMALL_STATE(17)] = 503,
  [SMALL_STATE(18)] = 546,
  [SMALL_STATE(19)] = 571,
  [SMALL_STATE(20)] = 614,
  [SMALL_STATE(21)] = 657,
  [SMALL_STATE(22)] = 680,
  [SMALL_STATE(23)] = 703,
  [SMALL_STATE(24)] = 726,
  [SMALL_STATE(25)] = 749,
  [SMALL_STATE(26)] = 772,
  [SMALL_STATE(27)] = 795,
  [SMALL_STATE(28)] = 818,
  [SMALL_STATE(29)] = 841,
  [SMALL_STATE(30)] = 867,
  [SMALL_STATE(31)] = 895,
  [SMALL_STATE(32)] = 923,
  [SMALL_STATE(33)] = 949,
  [SMALL_STATE(34)] = 983,
  [SMALL_STATE(35)] = 1017,
  [SMALL_STATE(36)] = 1041,
  [SMALL_STATE(37)] = 1067,
  [SMALL_STATE(38)] = 1091,
  [SMALL_STATE(39)] = 1115,
  [SMALL_STATE(40)] = 1137,
  [SMALL_STATE(41)] = 1155,
  [SMALL_STATE(42)] = 1183,
  [SMALL_STATE(43)] = 1211,
  [SMALL_STATE(44)] = 1233,
  [SMALL_STATE(45)] = 1255,
  [SMALL_STATE(46)] = 1277,
  [SMALL_STATE(47)] = 1299,
  [SMALL_STATE(48)] = 1319,
  [SMALL_STATE(49)] = 1341,
  [SMALL_STATE(50)] = 1369,
  [SMALL_STATE(51)] = 1387,
  [SMALL_STATE(52)] = 1415,
  [SMALL_STATE(53)] = 1435,
  [SMALL_STATE(54)] = 1454,
  [SMALL_STATE(55)] = 1479,
  [SMALL_STATE(56)] = 1504,
  [SMALL_STATE(57)] = 1521,
  [SMALL_STATE(58)] = 1538,
  [SMALL_STATE(59)] = 1555,
  [SMALL_STATE(60)] = 1578,
  [SMALL_STATE(61)] = 1595,
  [SMALL_STATE(62)] = 1618,
  [SMALL_STATE(63)] = 1643,
  [SMALL_STATE(64)] = 1660,
  [SMALL_STATE(65)] = 1677,
  [SMALL_STATE(66)] = 1694,
  [SMALL_STATE(67)] = 1711,
  [SMALL_STATE(68)] = 1734,
  [SMALL_STATE(69)] = 1751,
  [SMALL_STATE(70)] = 1768,
  [SMALL_STATE(71)] = 1785,
  [SMALL_STATE(72)] = 1802,
  [SMALL_STATE(73)] = 1825,
  [SMALL_STATE(74)] = 1841,
  [SMALL_STATE(75)] = 1857,
  [SMALL_STATE(76)] = 1873,
  [SMALL_STATE(77)] = 1889,
  [SMALL_STATE(78)] = 1905,
  [SMALL_STATE(79)] = 1921,
  [SMALL_STATE(80)] = 1937,
  [SMALL_STATE(81)] = 1953,
  [SMALL_STATE(82)] = 1969,
  [SMALL_STATE(83)] = 1985,
  [SMALL_STATE(84)] = 2001,
  [SMALL_STATE(85)] = 2017,
  [SMALL_STATE(86)] = 2032,
  [SMALL_STATE(87)] = 2046,
  [SMALL_STATE(88)] = 2060,
  [SMALL_STATE(89)] = 2074,
  [SMALL_STATE(90)] = 2088,
  [SMALL_STATE(91)] = 2102,
  [SMALL_STATE(92)] = 2116,
  [SMALL_STATE(93)] = 2130,
  [SMALL_STATE(94)] = 2144,
  [SMALL_STATE(95)] = 2158,
  [SMALL_STATE(96)] = 2172,
  [SMALL_STATE(97)] = 2186,
  [SMALL_STATE(98)] = 2200,
  [SMALL_STATE(99)] = 2209,
  [SMALL_STATE(100)] = 2220,
  [SMALL_STATE(101)] = 2231,
  [SMALL_STATE(102)] = 2242,
  [SMALL_STATE(103)] = 2253,
  [SMALL_STATE(104)] = 2264,
  [SMALL_STATE(105)] = 2275,
  [SMALL_STATE(106)] = 2286,
  [SMALL_STATE(107)] = 2295,
  [SMALL_STATE(108)] = 2306,
  [SMALL_STATE(109)] = 2317,
  [SMALL_STATE(110)] = 2325,
  [SMALL_STATE(111)] = 2333,
  [SMALL_STATE(112)] = 2341,
  [SMALL_STATE(113)] = 2349,
  [SMALL_STATE(114)] = 2357,
  [SMALL_STATE(115)] = 2365,
  [SMALL_STATE(116)] = 2373,
  [SMALL_STATE(117)] = 2381,
  [SMALL_STATE(118)] = 2389,
  [SMALL_STATE(119)] = 2397,
  [SMALL_STATE(120)] = 2405,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(107),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(116),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number_literal, 1, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number_literal, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number_literal, 2, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number_literal, 2, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 2, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 2, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(116),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(95),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(4),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(114),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(3),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(18),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 2, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 2, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(120),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(94),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 3, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 3, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 4, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 4, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [97] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(120),
  [100] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(94),
  [103] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(23),
  [106] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(115),
  [109] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(16),
  [112] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(24),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_initializer, 1, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_initializer, 1, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [125] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_statement, 1, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_statement, 1, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 2, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header, 2, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, SHIFT(101),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [155] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(107),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_header_repeat1, 2, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_header_repeat1, 2, 0, 0),
  [164] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_header_repeat1, 2, 0, 0), SHIFT_REPEAT(101),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 1, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header, 1, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declarator_list, 2, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declarator_list, 2, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_package_declaration, 3, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_package_declaration, 3, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_variable_declarator_list_repeat1, 2, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_variable_declarator_list_repeat1, 2, 0, 0),
  [191] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_variable_declarator_list_repeat1, 2, 0, 0), SHIFT_REPEAT(105),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declarator_list, 1, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declarator_list, 1, 0, 0),
  [198] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_variable_declarator_list_repeat1, 2, 0, 0), SHIFT_REPEAT(103),
  [201] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declarator, 1, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declarator, 1, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_statement, 3, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import_statement, 3, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_initializer_repeat1, 2, 0, 0),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_initializer, 3, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_initializer, 3, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_initializer, 2, 0, 0),
  [225] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_initializer, 2, 0, 0),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_initializer, 4, 0, 0),
  [233] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_initializer, 4, 0, 0),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [237] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declarator, 3, 0, 0),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declarator, 3, 0, 0),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [247] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [249] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1, 0, 0),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [255] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [257] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 2, 0, 0),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 2, 0, 0),
  [261] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_statement, 2, 0, 0),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_statement, 2, 0, 0),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_declaration, 4, 0, 0),
  [267] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_declaration, 4, 0, 0),
  [269] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_initializer_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_qualified_identifier_repeat1, 2, 0, 0),
  [278] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_qualified_identifier_repeat1, 2, 0, 0), SHIFT_REPEAT(119),
  [281] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0), SHIFT_REPEAT(113),
  [284] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [290] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_qualified_identifier, 1, 0, 0),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [304] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_qualified_identifier, 2, 0, 0),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [320] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [322] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 4, 0, 0),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [334] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2, 0, 0),
  [336] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 3, 0, 0),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_gosu(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
