#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 121
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 54
#define ALIAS_COUNT 0
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_package = 1,
  anon_sym_SEMI = 2,
  anon_sym_uses = 3,
  anon_sym_DOT = 4,
  anon_sym_function = 5,
  anon_sym_LPAREN = 6,
  anon_sym_COMMA = 7,
  anon_sym_RPAREN = 8,
  anon_sym_LBRACE = 9,
  anon_sym_RBRACE = 10,
  anon_sym_var = 11,
  anon_sym_EQ = 12,
  aux_sym_number_literal_token1 = 13,
  anon_sym_0x = 14,
  aux_sym_number_literal_token2 = 15,
  anon_sym_PLUS = 16,
  anon_sym_DASH = 17,
  anon_sym_STAR = 18,
  anon_sym_SLASH = 19,
  anon_sym_PERCENT = 20,
  anon_sym_EQ_EQ = 21,
  anon_sym_EQ_EQ_EQ = 22,
  sym_identifier = 23,
  sym_string = 24,
  sym_line_comment = 25,
  sym_block_comment = 26,
  sym_source_file = 27,
  sym_header = 28,
  sym_package_declaration = 29,
  sym_uses_statement = 30,
  sym_qualified_identifier = 31,
  sym_statement = 32,
  sym_function_declaration = 33,
  sym_parameter_list = 34,
  sym_block = 35,
  sym_variable_declaration = 36,
  sym_variable_declarator_list = 37,
  sym_variable_declarator = 38,
  sym_variable_initializer = 39,
  sym_array_initializer = 40,
  sym_expression_statement = 41,
  sym_expression = 42,
  sym_number_literal = 43,
  sym_binary_expression = 44,
  sym_function_call = 45,
  sym_argument_list = 46,
  aux_sym_source_file_repeat1 = 47,
  aux_sym_source_file_repeat2 = 48,
  aux_sym_header_repeat1 = 49,
  aux_sym_qualified_identifier_repeat1 = 50,
  aux_sym_parameter_list_repeat1 = 51,
  aux_sym_variable_declarator_list_repeat1 = 52,
  aux_sym_array_initializer_repeat1 = 53,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_package] = "package",
  [anon_sym_SEMI] = ";",
  [anon_sym_uses] = "uses",
  [anon_sym_DOT] = ".",
  [anon_sym_function] = "function",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_var] = "var",
  [anon_sym_EQ] = "=",
  [aux_sym_number_literal_token1] = "number_literal_token1",
  [anon_sym_0x] = "0x",
  [aux_sym_number_literal_token2] = "number_literal_token2",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PERCENT] = "%",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_EQ_EQ_EQ] = "===",
  [sym_identifier] = "identifier",
  [sym_string] = "string",
  [sym_line_comment] = "line_comment",
  [sym_block_comment] = "block_comment",
  [sym_source_file] = "source_file",
  [sym_header] = "header",
  [sym_package_declaration] = "package_declaration",
  [sym_uses_statement] = "uses_statement",
  [sym_qualified_identifier] = "qualified_identifier",
  [sym_statement] = "statement",
  [sym_function_declaration] = "function_declaration",
  [sym_parameter_list] = "parameter_list",
  [sym_block] = "block",
  [sym_variable_declaration] = "variable_declaration",
  [sym_variable_declarator_list] = "variable_declarator_list",
  [sym_variable_declarator] = "variable_declarator",
  [sym_variable_initializer] = "variable_initializer",
  [sym_array_initializer] = "array_initializer",
  [sym_expression_statement] = "expression_statement",
  [sym_expression] = "expression",
  [sym_number_literal] = "number_literal",
  [sym_binary_expression] = "binary_expression",
  [sym_function_call] = "function_call",
  [sym_argument_list] = "argument_list",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_source_file_repeat2] = "source_file_repeat2",
  [aux_sym_header_repeat1] = "header_repeat1",
  [aux_sym_qualified_identifier_repeat1] = "qualified_identifier_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [aux_sym_variable_declarator_list_repeat1] = "variable_declarator_list_repeat1",
  [aux_sym_array_initializer_repeat1] = "array_initializer_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_package] = anon_sym_package,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_uses] = anon_sym_uses,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_function] = anon_sym_function,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_var] = anon_sym_var,
  [anon_sym_EQ] = anon_sym_EQ,
  [aux_sym_number_literal_token1] = aux_sym_number_literal_token1,
  [anon_sym_0x] = anon_sym_0x,
  [aux_sym_number_literal_token2] = aux_sym_number_literal_token2,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_EQ_EQ_EQ] = anon_sym_EQ_EQ_EQ,
  [sym_identifier] = sym_identifier,
  [sym_string] = sym_string,
  [sym_line_comment] = sym_line_comment,
  [sym_block_comment] = sym_block_comment,
  [sym_source_file] = sym_source_file,
  [sym_header] = sym_header,
  [sym_package_declaration] = sym_package_declaration,
  [sym_uses_statement] = sym_uses_statement,
  [sym_qualified_identifier] = sym_qualified_identifier,
  [sym_statement] = sym_statement,
  [sym_function_declaration] = sym_function_declaration,
  [sym_parameter_list] = sym_parameter_list,
  [sym_block] = sym_block,
  [sym_variable_declaration] = sym_variable_declaration,
  [sym_variable_declarator_list] = sym_variable_declarator_list,
  [sym_variable_declarator] = sym_variable_declarator,
  [sym_variable_initializer] = sym_variable_initializer,
  [sym_array_initializer] = sym_array_initializer,
  [sym_expression_statement] = sym_expression_statement,
  [sym_expression] = sym_expression,
  [sym_number_literal] = sym_number_literal,
  [sym_binary_expression] = sym_binary_expression,
  [sym_function_call] = sym_function_call,
  [sym_argument_list] = sym_argument_list,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_source_file_repeat2] = aux_sym_source_file_repeat2,
  [aux_sym_header_repeat1] = aux_sym_header_repeat1,
  [aux_sym_qualified_identifier_repeat1] = aux_sym_qualified_identifier_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [aux_sym_variable_declarator_list_repeat1] = aux_sym_variable_declarator_list_repeat1,
  [aux_sym_array_initializer_repeat1] = aux_sym_array_initializer_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_package] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_uses] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_function] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_var] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_number_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_0x] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_number_literal_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_header] = {
    .visible = true,
    .named = true,
  },
  [sym_package_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_uses_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_qualified_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_function_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_declarator_list] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_declarator] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_initializer] = {
    .visible = true,
    .named = true,
  },
  [sym_array_initializer] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_number_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_header_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_qualified_identifier_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_variable_declarator_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_initializer_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 3,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 12,
  [16] = 16,
  [17] = 4,
  [18] = 18,
  [19] = 19,
  [20] = 5,
  [21] = 6,
  [22] = 14,
  [23] = 7,
  [24] = 8,
  [25] = 9,
  [26] = 18,
  [27] = 10,
  [28] = 19,
  [29] = 29,
  [30] = 30,
  [31] = 30,
  [32] = 29,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 40,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 45,
  [49] = 43,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 50,
  [56] = 52,
  [57] = 57,
  [58] = 57,
  [59] = 59,
  [60] = 54,
  [61] = 59,
  [62] = 62,
  [63] = 62,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 64,
  [69] = 69,
  [70] = 70,
  [71] = 66,
  [72] = 67,
  [73] = 65,
  [74] = 74,
  [75] = 75,
  [76] = 74,
  [77] = 75,
  [78] = 69,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 82,
  [84] = 80,
  [85] = 85,
  [86] = 86,
  [87] = 81,
  [88] = 85,
  [89] = 79,
  [90] = 86,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 92,
  [97] = 97,
  [98] = 98,
  [99] = 95,
  [100] = 98,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 102,
  [108] = 108,
  [109] = 103,
  [110] = 105,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 117,
  [120] = 115,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(14);
      ADVANCE_MAP(
        '"', 2,
        '%', 37,
        '(', 20,
        ')', 22,
        '*', 35,
        '+', 33,
        ',', 21,
        '-', 34,
        '.', 18,
        '/', 36,
        '0', 30,
        ';', 16,
        '=', 27,
        'f', 57,
        'p', 40,
        'u', 54,
        'v', 41,
        '{', 23,
        '}', 24,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == ')') ADVANCE(22);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '0') ADVANCE(30);
      if (lookahead == '{') ADVANCE(23);
      if (lookahead == '}') ADVANCE(24);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(59);
      if (lookahead == '\\') ADVANCE(11);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(60);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(61);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(32);
      END_STATE();
    case 7:
      if (lookahead == '=') ADVANCE(38);
      END_STATE();
    case 8:
      if (lookahead == '_') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 9:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(32);
      END_STATE();
    case 11:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 12:
      if (eof) ADVANCE(14);
      ADVANCE_MAP(
        '"', 2,
        '%', 37,
        '(', 20,
        ')', 22,
        '*', 35,
        '+', 33,
        ',', 21,
        '-', 34,
        '/', 36,
        '0', 30,
        ';', 16,
        '=', 7,
        'f', 57,
        'v', 41,
        '}', 24,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(12);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 13:
      if (eof) ADVANCE(14);
      ADVANCE_MAP(
        '"', 2,
        ',', 21,
        '/', 3,
        '0', 30,
        '=', 26,
        'f', 57,
        'v', 41,
        '}', 24,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(13);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_package);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_uses);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_function);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_var);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(38);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_number_literal_token1);
      if (lookahead == '_') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_number_literal_token1);
      if (lookahead == '_') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_number_literal_token1);
      if (lookahead == 'x') ADVANCE(31);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_0x);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_number_literal_token2);
      if (lookahead == '_') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(60);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      if (lookahead == '=') ADVANCE(39);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_EQ_EQ_EQ);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'k') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_block_comment);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 12},
  [4] = {.lex_state = 12},
  [5] = {.lex_state = 12},
  [6] = {.lex_state = 12},
  [7] = {.lex_state = 12},
  [8] = {.lex_state = 12},
  [9] = {.lex_state = 12},
  [10] = {.lex_state = 12},
  [11] = {.lex_state = 12},
  [12] = {.lex_state = 12},
  [13] = {.lex_state = 12},
  [14] = {.lex_state = 12},
  [15] = {.lex_state = 12},
  [16] = {.lex_state = 12},
  [17] = {.lex_state = 12},
  [18] = {.lex_state = 12},
  [19] = {.lex_state = 12},
  [20] = {.lex_state = 12},
  [21] = {.lex_state = 12},
  [22] = {.lex_state = 12},
  [23] = {.lex_state = 12},
  [24] = {.lex_state = 12},
  [25] = {.lex_state = 12},
  [26] = {.lex_state = 12},
  [27] = {.lex_state = 12},
  [28] = {.lex_state = 12},
  [29] = {.lex_state = 12},
  [30] = {.lex_state = 12},
  [31] = {.lex_state = 12},
  [32] = {.lex_state = 12},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 12},
  [44] = {.lex_state = 12},
  [45] = {.lex_state = 12},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 12},
  [49] = {.lex_state = 12},
  [50] = {.lex_state = 13},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 12},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 13},
  [56] = {.lex_state = 12},
  [57] = {.lex_state = 12},
  [58] = {.lex_state = 12},
  [59] = {.lex_state = 12},
  [60] = {.lex_state = 1},
  [61] = {.lex_state = 12},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 12},
  [65] = {.lex_state = 12},
  [66] = {.lex_state = 12},
  [67] = {.lex_state = 12},
  [68] = {.lex_state = 12},
  [69] = {.lex_state = 1},
  [70] = {.lex_state = 1},
  [71] = {.lex_state = 12},
  [72] = {.lex_state = 12},
  [73] = {.lex_state = 12},
  [74] = {.lex_state = 12},
  [75] = {.lex_state = 12},
  [76] = {.lex_state = 12},
  [77] = {.lex_state = 12},
  [78] = {.lex_state = 1},
  [79] = {.lex_state = 12},
  [80] = {.lex_state = 12},
  [81] = {.lex_state = 12},
  [82] = {.lex_state = 12},
  [83] = {.lex_state = 12},
  [84] = {.lex_state = 12},
  [85] = {.lex_state = 12},
  [86] = {.lex_state = 12},
  [87] = {.lex_state = 12},
  [88] = {.lex_state = 12},
  [89] = {.lex_state = 12},
  [90] = {.lex_state = 12},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 1},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 1},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 1},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 1},
  [104] = {.lex_state = 1},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 1},
  [109] = {.lex_state = 1},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 1},
  [114] = {.lex_state = 1},
  [115] = {.lex_state = 1},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 6},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 6},
  [120] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_package] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_uses] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_function] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_var] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [aux_sym_number_literal_token1] = ACTIONS(1),
    [anon_sym_0x] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(112),
    [sym_header] = STATE(2),
    [sym_package_declaration] = STATE(38),
    [sym_uses_statement] = STATE(38),
    [sym_statement] = STATE(13),
    [sym_function_declaration] = STATE(86),
    [sym_variable_declaration] = STATE(86),
    [sym_expression_statement] = STATE(86),
    [sym_expression] = STATE(30),
    [sym_number_literal] = STATE(4),
    [sym_binary_expression] = STATE(4),
    [sym_function_call] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(2),
    [aux_sym_source_file_repeat2] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_package] = ACTIONS(7),
    [anon_sym_uses] = ACTIONS(9),
    [anon_sym_function] = ACTIONS(11),
    [anon_sym_var] = ACTIONS(13),
    [aux_sym_number_literal_token1] = ACTIONS(15),
    [anon_sym_0x] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [sym_string] = ACTIONS(21),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 16,
    ACTIONS(7), 1,
      anon_sym_package,
    ACTIONS(9), 1,
      anon_sym_uses,
    ACTIONS(11), 1,
      anon_sym_function,
    ACTIONS(13), 1,
      anon_sym_var,
    ACTIONS(15), 1,
      aux_sym_number_literal_token1,
    ACTIONS(17), 1,
      anon_sym_0x,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_string,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    STATE(30), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(16), 2,
      sym_statement,
      aux_sym_source_file_repeat2,
    STATE(33), 2,
      sym_header,
      aux_sym_source_file_repeat1,
    STATE(38), 2,
      sym_package_declaration,
      sym_uses_statement,
    STATE(4), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
    STATE(86), 3,
      sym_function_declaration,
      sym_variable_declaration,
      sym_expression_statement,
  [57] = 5,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    STATE(6), 1,
      sym_argument_list,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(27), 6,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      sym_identifier,
    ACTIONS(25), 12,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
      sym_string,
  [90] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(27), 6,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      sym_identifier,
    ACTIONS(25), 12,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
      sym_string,
  [117] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(33), 6,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      sym_identifier,
    ACTIONS(31), 12,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
      sym_string,
  [144] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(37), 6,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      sym_identifier,
    ACTIONS(35), 12,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
      sym_string,
  [171] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(41), 6,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      sym_identifier,
    ACTIONS(39), 12,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
      sym_string,
  [198] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(45), 6,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      sym_identifier,
    ACTIONS(43), 12,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
      sym_string,
  [225] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(49), 6,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      sym_identifier,
    ACTIONS(47), 12,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
      sym_string,
  [252] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(53), 6,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      sym_identifier,
    ACTIONS(51), 12,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
      sym_string,
  [279] = 5,
    ACTIONS(55), 1,
      anon_sym_LPAREN,
    STATE(21), 1,
      sym_argument_list,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(27), 6,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      sym_identifier,
    ACTIONS(25), 10,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
      sym_string,
  [310] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(59), 6,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      sym_identifier,
    ACTIONS(57), 12,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
      sym_string,
  [337] = 12,
    ACTIONS(11), 1,
      anon_sym_function,
    ACTIONS(13), 1,
      anon_sym_var,
    ACTIONS(15), 1,
      aux_sym_number_literal_token1,
    ACTIONS(17), 1,
      anon_sym_0x,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_string,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    STATE(30), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(14), 2,
      sym_statement,
      aux_sym_source_file_repeat2,
    STATE(4), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
    STATE(86), 3,
      sym_function_declaration,
      sym_variable_declaration,
      sym_expression_statement,
  [380] = 12,
    ACTIONS(61), 1,
      ts_builtin_sym_end,
    ACTIONS(63), 1,
      anon_sym_function,
    ACTIONS(66), 1,
      anon_sym_var,
    ACTIONS(69), 1,
      aux_sym_number_literal_token1,
    ACTIONS(72), 1,
      anon_sym_0x,
    ACTIONS(75), 1,
      sym_identifier,
    ACTIONS(78), 1,
      sym_string,
    STATE(30), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(14), 2,
      sym_statement,
      aux_sym_source_file_repeat2,
    STATE(4), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
    STATE(86), 3,
      sym_function_declaration,
      sym_variable_declaration,
      sym_expression_statement,
  [423] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(59), 6,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      sym_identifier,
    ACTIONS(57), 10,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
      sym_string,
  [448] = 12,
    ACTIONS(11), 1,
      anon_sym_function,
    ACTIONS(13), 1,
      anon_sym_var,
    ACTIONS(15), 1,
      aux_sym_number_literal_token1,
    ACTIONS(17), 1,
      anon_sym_0x,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_string,
    ACTIONS(81), 1,
      ts_builtin_sym_end,
    STATE(30), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(14), 2,
      sym_statement,
      aux_sym_source_file_repeat2,
    STATE(4), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
    STATE(86), 3,
      sym_function_declaration,
      sym_variable_declaration,
      sym_expression_statement,
  [491] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(27), 6,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      sym_identifier,
    ACTIONS(25), 10,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
      sym_string,
  [516] = 12,
    ACTIONS(83), 1,
      anon_sym_function,
    ACTIONS(85), 1,
      anon_sym_RBRACE,
    ACTIONS(87), 1,
      anon_sym_var,
    ACTIONS(89), 1,
      aux_sym_number_literal_token1,
    ACTIONS(91), 1,
      anon_sym_0x,
    ACTIONS(93), 1,
      sym_identifier,
    ACTIONS(95), 1,
      sym_string,
    STATE(31), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(19), 2,
      sym_statement,
      aux_sym_source_file_repeat2,
    STATE(17), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
    STATE(90), 3,
      sym_function_declaration,
      sym_variable_declaration,
      sym_expression_statement,
  [559] = 12,
    ACTIONS(83), 1,
      anon_sym_function,
    ACTIONS(87), 1,
      anon_sym_var,
    ACTIONS(89), 1,
      aux_sym_number_literal_token1,
    ACTIONS(91), 1,
      anon_sym_0x,
    ACTIONS(93), 1,
      sym_identifier,
    ACTIONS(95), 1,
      sym_string,
    ACTIONS(97), 1,
      anon_sym_RBRACE,
    STATE(31), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(22), 2,
      sym_statement,
      aux_sym_source_file_repeat2,
    STATE(17), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
    STATE(90), 3,
      sym_function_declaration,
      sym_variable_declaration,
      sym_expression_statement,
  [602] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(33), 6,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      sym_identifier,
    ACTIONS(31), 10,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
      sym_string,
  [627] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(37), 6,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      sym_identifier,
    ACTIONS(35), 10,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
      sym_string,
  [652] = 12,
    ACTIONS(61), 1,
      anon_sym_RBRACE,
    ACTIONS(99), 1,
      anon_sym_function,
    ACTIONS(102), 1,
      anon_sym_var,
    ACTIONS(105), 1,
      aux_sym_number_literal_token1,
    ACTIONS(108), 1,
      anon_sym_0x,
    ACTIONS(111), 1,
      sym_identifier,
    ACTIONS(114), 1,
      sym_string,
    STATE(31), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(22), 2,
      sym_statement,
      aux_sym_source_file_repeat2,
    STATE(17), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
    STATE(90), 3,
      sym_function_declaration,
      sym_variable_declaration,
      sym_expression_statement,
  [695] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(41), 6,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      sym_identifier,
    ACTIONS(39), 10,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
      sym_string,
  [720] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(45), 6,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      sym_identifier,
    ACTIONS(43), 10,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
      sym_string,
  [745] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(49), 6,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      sym_identifier,
    ACTIONS(47), 10,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
      sym_string,
  [770] = 12,
    ACTIONS(83), 1,
      anon_sym_function,
    ACTIONS(87), 1,
      anon_sym_var,
    ACTIONS(89), 1,
      aux_sym_number_literal_token1,
    ACTIONS(91), 1,
      anon_sym_0x,
    ACTIONS(93), 1,
      sym_identifier,
    ACTIONS(95), 1,
      sym_string,
    ACTIONS(117), 1,
      anon_sym_RBRACE,
    STATE(31), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(28), 2,
      sym_statement,
      aux_sym_source_file_repeat2,
    STATE(17), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
    STATE(90), 3,
      sym_function_declaration,
      sym_variable_declaration,
      sym_expression_statement,
  [813] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(53), 6,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      sym_identifier,
    ACTIONS(51), 10,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
      sym_string,
  [838] = 12,
    ACTIONS(83), 1,
      anon_sym_function,
    ACTIONS(87), 1,
      anon_sym_var,
    ACTIONS(89), 1,
      aux_sym_number_literal_token1,
    ACTIONS(91), 1,
      anon_sym_0x,
    ACTIONS(93), 1,
      sym_identifier,
    ACTIONS(95), 1,
      sym_string,
    ACTIONS(119), 1,
      anon_sym_RBRACE,
    STATE(31), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(22), 2,
      sym_statement,
      aux_sym_source_file_repeat2,
    STATE(17), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
    STATE(90), 3,
      sym_function_declaration,
      sym_variable_declaration,
      sym_expression_statement,
  [881] = 5,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(127), 2,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
    ACTIONS(121), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_0x,
      sym_string,
    ACTIONS(123), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
    ACTIONS(125), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
  [909] = 6,
    ACTIONS(131), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(127), 2,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
    ACTIONS(129), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    ACTIONS(133), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
    ACTIONS(125), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
  [939] = 6,
    ACTIONS(135), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(139), 2,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
    ACTIONS(129), 3,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
    ACTIONS(133), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
    ACTIONS(137), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
  [969] = 5,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(139), 2,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
    ACTIONS(121), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
    ACTIONS(123), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
    ACTIONS(137), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
  [997] = 7,
    ACTIONS(143), 1,
      anon_sym_package,
    ACTIONS(146), 1,
      anon_sym_uses,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(33), 2,
      sym_header,
      aux_sym_source_file_repeat1,
    STATE(38), 2,
      sym_package_declaration,
      sym_uses_statement,
    ACTIONS(141), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    ACTIONS(149), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1027] = 5,
    ACTIONS(155), 1,
      anon_sym_DOT,
    STATE(37), 1,
      aux_sym_qualified_identifier_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(151), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_0x,
      sym_string,
    ACTIONS(153), 6,
      anon_sym_package,
      anon_sym_uses,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1052] = 4,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(157), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    STATE(36), 3,
      sym_package_declaration,
      sym_uses_statement,
      aux_sym_header_repeat1,
    ACTIONS(159), 6,
      anon_sym_package,
      anon_sym_uses,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1075] = 6,
    ACTIONS(163), 1,
      anon_sym_package,
    ACTIONS(166), 1,
      anon_sym_uses,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(161), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    STATE(36), 3,
      sym_package_declaration,
      sym_uses_statement,
      aux_sym_header_repeat1,
    ACTIONS(169), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1102] = 5,
    ACTIONS(175), 1,
      anon_sym_DOT,
    STATE(37), 1,
      aux_sym_qualified_identifier_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(171), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_0x,
      sym_string,
    ACTIONS(173), 6,
      anon_sym_package,
      anon_sym_uses,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1127] = 4,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(178), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    STATE(35), 3,
      sym_package_declaration,
      sym_uses_statement,
      aux_sym_header_repeat1,
    ACTIONS(180), 6,
      anon_sym_package,
      anon_sym_uses,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1150] = 5,
    ACTIONS(155), 1,
      anon_sym_DOT,
    STATE(34), 1,
      aux_sym_qualified_identifier_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(182), 4,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_0x,
      sym_string,
    ACTIONS(184), 6,
      anon_sym_package,
      anon_sym_uses,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1175] = 10,
    ACTIONS(15), 1,
      aux_sym_number_literal_token1,
    ACTIONS(17), 1,
      anon_sym_0x,
    ACTIONS(21), 1,
      sym_string,
    ACTIONS(186), 1,
      anon_sym_LBRACE,
    ACTIONS(188), 1,
      sym_identifier,
    STATE(29), 1,
      sym_expression,
    STATE(74), 1,
      sym_array_initializer,
    STATE(77), 1,
      sym_variable_initializer,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(4), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
  [1209] = 10,
    ACTIONS(89), 1,
      aux_sym_number_literal_token1,
    ACTIONS(91), 1,
      anon_sym_0x,
    ACTIONS(95), 1,
      sym_string,
    ACTIONS(190), 1,
      anon_sym_LBRACE,
    ACTIONS(192), 1,
      sym_identifier,
    STATE(32), 1,
      sym_expression,
    STATE(75), 1,
      sym_variable_initializer,
    STATE(76), 1,
      sym_array_initializer,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(17), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
  [1243] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(171), 5,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_DOT,
      anon_sym_0x,
      sym_string,
    ACTIONS(173), 6,
      anon_sym_package,
      anon_sym_uses,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1263] = 6,
    ACTIONS(194), 1,
      anon_sym_COMMA,
    ACTIONS(196), 1,
      anon_sym_RBRACE,
    STATE(98), 1,
      aux_sym_array_initializer_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(127), 2,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
    ACTIONS(125), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
  [1288] = 4,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(127), 2,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
    ACTIONS(198), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
    ACTIONS(125), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
  [1309] = 6,
    ACTIONS(194), 1,
      anon_sym_COMMA,
    ACTIONS(200), 1,
      anon_sym_RPAREN,
    STATE(95), 1,
      aux_sym_array_initializer_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(127), 2,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
    ACTIONS(125), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
  [1334] = 4,
    ACTIONS(206), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(202), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    ACTIONS(204), 6,
      anon_sym_package,
      anon_sym_uses,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1355] = 4,
    ACTIONS(212), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(208), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    ACTIONS(210), 6,
      anon_sym_package,
      anon_sym_uses,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1376] = 6,
    ACTIONS(194), 1,
      anon_sym_COMMA,
    ACTIONS(214), 1,
      anon_sym_RPAREN,
    STATE(99), 1,
      aux_sym_array_initializer_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(127), 2,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
    ACTIONS(125), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
  [1401] = 6,
    ACTIONS(194), 1,
      anon_sym_COMMA,
    ACTIONS(216), 1,
      anon_sym_RBRACE,
    STATE(100), 1,
      aux_sym_array_initializer_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(127), 2,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
    ACTIONS(125), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
  [1426] = 4,
    ACTIONS(222), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(218), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_0x,
      sym_string,
    ACTIONS(220), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1446] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(224), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    ACTIONS(226), 6,
      anon_sym_package,
      anon_sym_uses,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1464] = 5,
    ACTIONS(232), 1,
      anon_sym_COMMA,
    STATE(57), 1,
      aux_sym_variable_declarator_list_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(228), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    ACTIONS(230), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1486] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(234), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    ACTIONS(236), 6,
      anon_sym_package,
      anon_sym_uses,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1504] = 8,
    ACTIONS(15), 1,
      aux_sym_number_literal_token1,
    ACTIONS(17), 1,
      anon_sym_0x,
    ACTIONS(21), 1,
      sym_string,
    ACTIONS(188), 1,
      sym_identifier,
    ACTIONS(238), 1,
      anon_sym_RPAREN,
    STATE(45), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(4), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
  [1532] = 4,
    ACTIONS(240), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(218), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
    ACTIONS(220), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1552] = 5,
    ACTIONS(242), 1,
      anon_sym_COMMA,
    STATE(58), 1,
      aux_sym_variable_declarator_list_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(228), 3,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
    ACTIONS(230), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1574] = 5,
    ACTIONS(232), 1,
      anon_sym_COMMA,
    STATE(59), 1,
      aux_sym_variable_declarator_list_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(244), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    ACTIONS(246), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1596] = 5,
    ACTIONS(242), 1,
      anon_sym_COMMA,
    STATE(61), 1,
      aux_sym_variable_declarator_list_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(244), 3,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
    ACTIONS(246), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1618] = 5,
    ACTIONS(252), 1,
      anon_sym_COMMA,
    STATE(59), 1,
      aux_sym_variable_declarator_list_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(248), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    ACTIONS(250), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1640] = 8,
    ACTIONS(15), 1,
      aux_sym_number_literal_token1,
    ACTIONS(17), 1,
      anon_sym_0x,
    ACTIONS(21), 1,
      sym_string,
    ACTIONS(188), 1,
      sym_identifier,
    ACTIONS(255), 1,
      anon_sym_RPAREN,
    STATE(48), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(4), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
  [1668] = 5,
    ACTIONS(257), 1,
      anon_sym_COMMA,
    STATE(61), 1,
      aux_sym_variable_declarator_list_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(248), 3,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
    ACTIONS(250), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1690] = 8,
    ACTIONS(15), 1,
      aux_sym_number_literal_token1,
    ACTIONS(17), 1,
      anon_sym_0x,
    ACTIONS(21), 1,
      sym_string,
    ACTIONS(188), 1,
      sym_identifier,
    ACTIONS(260), 1,
      anon_sym_RBRACE,
    STATE(43), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(4), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
  [1718] = 8,
    ACTIONS(15), 1,
      aux_sym_number_literal_token1,
    ACTIONS(17), 1,
      anon_sym_0x,
    ACTIONS(21), 1,
      sym_string,
    ACTIONS(188), 1,
      sym_identifier,
    ACTIONS(262), 1,
      anon_sym_RBRACE,
    STATE(49), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(4), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
  [1746] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(264), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
    ACTIONS(266), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
  [1763] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(248), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
    ACTIONS(250), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1780] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(268), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_0x,
      sym_string,
    ACTIONS(270), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1797] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(272), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_0x,
      sym_string,
    ACTIONS(274), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1814] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(264), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
    ACTIONS(266), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_0x,
      sym_string,
  [1831] = 7,
    ACTIONS(15), 1,
      aux_sym_number_literal_token1,
    ACTIONS(17), 1,
      anon_sym_0x,
    ACTIONS(21), 1,
      sym_string,
    ACTIONS(188), 1,
      sym_identifier,
    STATE(8), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(4), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
  [1856] = 7,
    ACTIONS(15), 1,
      aux_sym_number_literal_token1,
    ACTIONS(17), 1,
      anon_sym_0x,
    ACTIONS(21), 1,
      sym_string,
    ACTIONS(188), 1,
      sym_identifier,
    STATE(44), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(4), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
  [1881] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(268), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
    ACTIONS(270), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1898] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(272), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
    ACTIONS(274), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1915] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(248), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_0x,
      sym_string,
    ACTIONS(250), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1932] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(121), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_0x,
      sym_string,
    ACTIONS(123), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1949] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(276), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
    ACTIONS(278), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
  [1966] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(121), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
    ACTIONS(123), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1983] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(276), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
    ACTIONS(278), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_0x,
      sym_string,
  [2000] = 7,
    ACTIONS(89), 1,
      aux_sym_number_literal_token1,
    ACTIONS(91), 1,
      anon_sym_0x,
    ACTIONS(95), 1,
      sym_string,
    ACTIONS(192), 1,
      sym_identifier,
    STATE(24), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(17), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
  [2025] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(282), 3,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
    ACTIONS(280), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [2041] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(284), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    ACTIONS(286), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [2057] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(290), 3,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
    ACTIONS(288), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [2073] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(294), 3,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
    ACTIONS(292), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [2089] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(294), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    ACTIONS(292), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [2105] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(284), 3,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
    ACTIONS(286), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [2121] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(296), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    ACTIONS(298), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [2137] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(300), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    ACTIONS(302), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [2153] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(290), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    ACTIONS(288), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [2169] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(296), 3,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
    ACTIONS(298), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [2185] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(282), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    ACTIONS(280), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [2201] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(300), 3,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
    ACTIONS(302), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [2217] = 4,
    ACTIONS(304), 1,
      anon_sym_COMMA,
    STATE(91), 1,
      aux_sym_array_initializer_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(198), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [2232] = 4,
    ACTIONS(307), 1,
      sym_identifier,
    STATE(52), 1,
      sym_variable_declarator,
    STATE(87), 1,
      sym_variable_declarator_list,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2246] = 4,
    ACTIONS(309), 1,
      anon_sym_COMMA,
    ACTIONS(311), 1,
      anon_sym_RPAREN,
    STATE(94), 1,
      aux_sym_parameter_list_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2260] = 4,
    ACTIONS(313), 1,
      anon_sym_COMMA,
    ACTIONS(316), 1,
      anon_sym_RPAREN,
    STATE(94), 1,
      aux_sym_parameter_list_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2274] = 4,
    ACTIONS(194), 1,
      anon_sym_COMMA,
    ACTIONS(318), 1,
      anon_sym_RPAREN,
    STATE(91), 1,
      aux_sym_array_initializer_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2288] = 4,
    ACTIONS(320), 1,
      sym_identifier,
    STATE(56), 1,
      sym_variable_declarator,
    STATE(81), 1,
      sym_variable_declarator_list,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2302] = 4,
    ACTIONS(309), 1,
      anon_sym_COMMA,
    ACTIONS(322), 1,
      anon_sym_RPAREN,
    STATE(93), 1,
      aux_sym_parameter_list_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2316] = 4,
    ACTIONS(194), 1,
      anon_sym_COMMA,
    ACTIONS(324), 1,
      anon_sym_RBRACE,
    STATE(91), 1,
      aux_sym_array_initializer_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2330] = 4,
    ACTIONS(194), 1,
      anon_sym_COMMA,
    ACTIONS(326), 1,
      anon_sym_RPAREN,
    STATE(91), 1,
      aux_sym_array_initializer_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2344] = 4,
    ACTIONS(194), 1,
      anon_sym_COMMA,
    ACTIONS(328), 1,
      anon_sym_RBRACE,
    STATE(91), 1,
      aux_sym_array_initializer_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2358] = 3,
    ACTIONS(330), 1,
      anon_sym_RPAREN,
    ACTIONS(332), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2369] = 3,
    ACTIONS(334), 1,
      anon_sym_LBRACE,
    STATE(80), 1,
      sym_block,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2380] = 3,
    ACTIONS(307), 1,
      sym_identifier,
    STATE(73), 1,
      sym_variable_declarator,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2391] = 3,
    ACTIONS(336), 1,
      sym_identifier,
    STATE(47), 1,
      sym_qualified_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2402] = 3,
    ACTIONS(338), 1,
      anon_sym_LPAREN,
    STATE(102), 1,
      sym_parameter_list,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2413] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(316), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2422] = 3,
    ACTIONS(340), 1,
      anon_sym_LBRACE,
    STATE(84), 1,
      sym_block,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2433] = 3,
    ACTIONS(336), 1,
      sym_identifier,
    STATE(46), 1,
      sym_qualified_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2444] = 3,
    ACTIONS(320), 1,
      sym_identifier,
    STATE(65), 1,
      sym_variable_declarator,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2455] = 3,
    ACTIONS(338), 1,
      anon_sym_LPAREN,
    STATE(107), 1,
      sym_parameter_list,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2466] = 2,
    ACTIONS(342), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2474] = 2,
    ACTIONS(344), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2482] = 2,
    ACTIONS(346), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2490] = 2,
    ACTIONS(348), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2498] = 2,
    ACTIONS(350), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2506] = 2,
    ACTIONS(352), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2514] = 2,
    ACTIONS(354), 1,
      aux_sym_number_literal_token2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2522] = 2,
    ACTIONS(356), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2530] = 2,
    ACTIONS(358), 1,
      aux_sym_number_literal_token2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2538] = 2,
    ACTIONS(360), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 57,
  [SMALL_STATE(4)] = 90,
  [SMALL_STATE(5)] = 117,
  [SMALL_STATE(6)] = 144,
  [SMALL_STATE(7)] = 171,
  [SMALL_STATE(8)] = 198,
  [SMALL_STATE(9)] = 225,
  [SMALL_STATE(10)] = 252,
  [SMALL_STATE(11)] = 279,
  [SMALL_STATE(12)] = 310,
  [SMALL_STATE(13)] = 337,
  [SMALL_STATE(14)] = 380,
  [SMALL_STATE(15)] = 423,
  [SMALL_STATE(16)] = 448,
  [SMALL_STATE(17)] = 491,
  [SMALL_STATE(18)] = 516,
  [SMALL_STATE(19)] = 559,
  [SMALL_STATE(20)] = 602,
  [SMALL_STATE(21)] = 627,
  [SMALL_STATE(22)] = 652,
  [SMALL_STATE(23)] = 695,
  [SMALL_STATE(24)] = 720,
  [SMALL_STATE(25)] = 745,
  [SMALL_STATE(26)] = 770,
  [SMALL_STATE(27)] = 813,
  [SMALL_STATE(28)] = 838,
  [SMALL_STATE(29)] = 881,
  [SMALL_STATE(30)] = 909,
  [SMALL_STATE(31)] = 939,
  [SMALL_STATE(32)] = 969,
  [SMALL_STATE(33)] = 997,
  [SMALL_STATE(34)] = 1027,
  [SMALL_STATE(35)] = 1052,
  [SMALL_STATE(36)] = 1075,
  [SMALL_STATE(37)] = 1102,
  [SMALL_STATE(38)] = 1127,
  [SMALL_STATE(39)] = 1150,
  [SMALL_STATE(40)] = 1175,
  [SMALL_STATE(41)] = 1209,
  [SMALL_STATE(42)] = 1243,
  [SMALL_STATE(43)] = 1263,
  [SMALL_STATE(44)] = 1288,
  [SMALL_STATE(45)] = 1309,
  [SMALL_STATE(46)] = 1334,
  [SMALL_STATE(47)] = 1355,
  [SMALL_STATE(48)] = 1376,
  [SMALL_STATE(49)] = 1401,
  [SMALL_STATE(50)] = 1426,
  [SMALL_STATE(51)] = 1446,
  [SMALL_STATE(52)] = 1464,
  [SMALL_STATE(53)] = 1486,
  [SMALL_STATE(54)] = 1504,
  [SMALL_STATE(55)] = 1532,
  [SMALL_STATE(56)] = 1552,
  [SMALL_STATE(57)] = 1574,
  [SMALL_STATE(58)] = 1596,
  [SMALL_STATE(59)] = 1618,
  [SMALL_STATE(60)] = 1640,
  [SMALL_STATE(61)] = 1668,
  [SMALL_STATE(62)] = 1690,
  [SMALL_STATE(63)] = 1718,
  [SMALL_STATE(64)] = 1746,
  [SMALL_STATE(65)] = 1763,
  [SMALL_STATE(66)] = 1780,
  [SMALL_STATE(67)] = 1797,
  [SMALL_STATE(68)] = 1814,
  [SMALL_STATE(69)] = 1831,
  [SMALL_STATE(70)] = 1856,
  [SMALL_STATE(71)] = 1881,
  [SMALL_STATE(72)] = 1898,
  [SMALL_STATE(73)] = 1915,
  [SMALL_STATE(74)] = 1932,
  [SMALL_STATE(75)] = 1949,
  [SMALL_STATE(76)] = 1966,
  [SMALL_STATE(77)] = 1983,
  [SMALL_STATE(78)] = 2000,
  [SMALL_STATE(79)] = 2025,
  [SMALL_STATE(80)] = 2041,
  [SMALL_STATE(81)] = 2057,
  [SMALL_STATE(82)] = 2073,
  [SMALL_STATE(83)] = 2089,
  [SMALL_STATE(84)] = 2105,
  [SMALL_STATE(85)] = 2121,
  [SMALL_STATE(86)] = 2137,
  [SMALL_STATE(87)] = 2153,
  [SMALL_STATE(88)] = 2169,
  [SMALL_STATE(89)] = 2185,
  [SMALL_STATE(90)] = 2201,
  [SMALL_STATE(91)] = 2217,
  [SMALL_STATE(92)] = 2232,
  [SMALL_STATE(93)] = 2246,
  [SMALL_STATE(94)] = 2260,
  [SMALL_STATE(95)] = 2274,
  [SMALL_STATE(96)] = 2288,
  [SMALL_STATE(97)] = 2302,
  [SMALL_STATE(98)] = 2316,
  [SMALL_STATE(99)] = 2330,
  [SMALL_STATE(100)] = 2344,
  [SMALL_STATE(101)] = 2358,
  [SMALL_STATE(102)] = 2369,
  [SMALL_STATE(103)] = 2380,
  [SMALL_STATE(104)] = 2391,
  [SMALL_STATE(105)] = 2402,
  [SMALL_STATE(106)] = 2413,
  [SMALL_STATE(107)] = 2422,
  [SMALL_STATE(108)] = 2433,
  [SMALL_STATE(109)] = 2444,
  [SMALL_STATE(110)] = 2455,
  [SMALL_STATE(111)] = 2466,
  [SMALL_STATE(112)] = 2474,
  [SMALL_STATE(113)] = 2482,
  [SMALL_STATE(114)] = 2490,
  [SMALL_STATE(115)] = 2498,
  [SMALL_STATE(116)] = 2506,
  [SMALL_STATE(117)] = 2514,
  [SMALL_STATE(118)] = 2522,
  [SMALL_STATE(119)] = 2530,
  [SMALL_STATE(120)] = 2538,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(108),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(104),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(115),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number_literal, 2, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number_literal, 2, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 2, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 2, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 2, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 2, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 3, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 3, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 4, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 4, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number_literal, 1, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number_literal, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0),
  [63] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(115),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(92),
  [69] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(12),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(119),
  [75] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(3),
  [78] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(4),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(120),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(96),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [99] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(120),
  [102] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(96),
  [105] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(15),
  [108] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(117),
  [111] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(11),
  [114] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(17),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_initializer, 1, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_initializer, 1, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [127] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_statement, 1, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_statement, 1, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [139] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [143] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(108),
  [146] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(104),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_qualified_identifier, 2, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_qualified_identifier, 2, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 2, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header, 2, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_header_repeat1, 2, 0, 0),
  [163] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_header_repeat1, 2, 0, 0), SHIFT_REPEAT(108),
  [166] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_header_repeat1, 2, 0, 0), SHIFT_REPEAT(104),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_header_repeat1, 2, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_qualified_identifier_repeat1, 2, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_qualified_identifier_repeat1, 2, 0, 0),
  [175] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_qualified_identifier_repeat1, 2, 0, 0), SHIFT_REPEAT(113),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 1, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header, 1, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_qualified_identifier, 1, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_qualified_identifier, 1, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_initializer_repeat1, 2, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_package_declaration, 2, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_package_declaration, 2, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_uses_statement, 2, 0, 0),
  [210] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_uses_statement, 2, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declarator, 1, 0, 0),
  [220] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declarator, 1, 0, 0),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_package_declaration, 3, 0, 0),
  [226] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_package_declaration, 3, 0, 0),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declarator_list, 1, 0, 0),
  [230] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declarator_list, 1, 0, 0),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_uses_statement, 3, 0, 0),
  [236] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_uses_statement, 3, 0, 0),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declarator_list, 2, 0, 0),
  [246] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declarator_list, 2, 0, 0),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_variable_declarator_list_repeat1, 2, 0, 0),
  [250] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_variable_declarator_list_repeat1, 2, 0, 0),
  [252] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_variable_declarator_list_repeat1, 2, 0, 0), SHIFT_REPEAT(103),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [257] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_variable_declarator_list_repeat1, 2, 0, 0), SHIFT_REPEAT(109),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [264] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_initializer, 2, 0, 0),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_initializer, 2, 0, 0),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_initializer, 3, 0, 0),
  [270] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_initializer, 3, 0, 0),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_initializer, 4, 0, 0),
  [274] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_initializer, 4, 0, 0),
  [276] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declarator, 3, 0, 0),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declarator, 3, 0, 0),
  [280] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [282] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [284] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_declaration, 4, 0, 0),
  [286] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_declaration, 4, 0, 0),
  [288] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 2, 0, 0),
  [290] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 2, 0, 0),
  [292] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_statement, 2, 0, 0),
  [294] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_statement, 2, 0, 0),
  [296] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [298] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [300] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [302] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1, 0, 0),
  [304] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_initializer_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [313] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0), SHIFT_REPEAT(114),
  [316] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [342] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 3, 0, 0),
  [344] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [350] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [352] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 4, 0, 0),
  [354] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [356] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2, 0, 0),
  [358] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [360] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_gosu(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
