#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 121
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 54
#define ALIAS_COUNT 0
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_package = 1,
  anon_sym_SEMI = 2,
  anon_sym_uses = 3,
  anon_sym_DOT = 4,
  anon_sym_function = 5,
  anon_sym_LPAREN = 6,
  anon_sym_COMMA = 7,
  anon_sym_RPAREN = 8,
  anon_sym_LBRACE = 9,
  anon_sym_RBRACE = 10,
  anon_sym_var = 11,
  anon_sym_EQ = 12,
  aux_sym_number_literal_token1 = 13,
  anon_sym_0x = 14,
  aux_sym_number_literal_token2 = 15,
  anon_sym_PLUS = 16,
  anon_sym_DASH = 17,
  anon_sym_STAR = 18,
  anon_sym_SLASH = 19,
  anon_sym_PERCENT = 20,
  anon_sym_EQ_EQ = 21,
  anon_sym_EQ_EQ_EQ = 22,
  sym_identifier = 23,
  sym_string = 24,
  sym_line_comment = 25,
  sym_block_comment = 26,
  sym_source_file = 27,
  sym_header = 28,
  sym_package_declaration = 29,
  sym_uses_statement = 30,
  sym_qualified_identifier = 31,
  sym_statement = 32,
  sym_function_declaration = 33,
  sym_parameter_list = 34,
  sym_block = 35,
  sym_variable_declaration = 36,
  sym_variable_declarator_list = 37,
  sym_variable_declarator = 38,
  sym_variable_initializer = 39,
  sym_array_initializer = 40,
  sym_expression_statement = 41,
  sym_expression = 42,
  sym_number_literal = 43,
  sym_binary_expression = 44,
  sym_function_call = 45,
  sym_argument_list = 46,
  aux_sym_source_file_repeat1 = 47,
  aux_sym_source_file_repeat2 = 48,
  aux_sym_header_repeat1 = 49,
  aux_sym_qualified_identifier_repeat1 = 50,
  aux_sym_parameter_list_repeat1 = 51,
  aux_sym_variable_declarator_list_repeat1 = 52,
  aux_sym_array_initializer_repeat1 = 53,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_package] = "package",
  [anon_sym_SEMI] = ";",
  [anon_sym_uses] = "uses",
  [anon_sym_DOT] = ".",
  [anon_sym_function] = "function",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_var] = "var",
  [anon_sym_EQ] = "=",
  [aux_sym_number_literal_token1] = "number_literal_token1",
  [anon_sym_0x] = "0x",
  [aux_sym_number_literal_token2] = "number_literal_token2",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PERCENT] = "%",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_EQ_EQ_EQ] = "===",
  [sym_identifier] = "identifier",
  [sym_string] = "string",
  [sym_line_comment] = "line_comment",
  [sym_block_comment] = "block_comment",
  [sym_source_file] = "source_file",
  [sym_header] = "header",
  [sym_package_declaration] = "package_declaration",
  [sym_uses_statement] = "uses_statement",
  [sym_qualified_identifier] = "qualified_identifier",
  [sym_statement] = "statement",
  [sym_function_declaration] = "function_declaration",
  [sym_parameter_list] = "parameter_list",
  [sym_block] = "block",
  [sym_variable_declaration] = "variable_declaration",
  [sym_variable_declarator_list] = "variable_declarator_list",
  [sym_variable_declarator] = "variable_declarator",
  [sym_variable_initializer] = "variable_initializer",
  [sym_array_initializer] = "array_initializer",
  [sym_expression_statement] = "expression_statement",
  [sym_expression] = "expression",
  [sym_number_literal] = "number_literal",
  [sym_binary_expression] = "binary_expression",
  [sym_function_call] = "function_call",
  [sym_argument_list] = "argument_list",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_source_file_repeat2] = "source_file_repeat2",
  [aux_sym_header_repeat1] = "header_repeat1",
  [aux_sym_qualified_identifier_repeat1] = "qualified_identifier_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [aux_sym_variable_declarator_list_repeat1] = "variable_declarator_list_repeat1",
  [aux_sym_array_initializer_repeat1] = "array_initializer_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_package] = anon_sym_package,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_uses] = anon_sym_uses,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_function] = anon_sym_function,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_var] = anon_sym_var,
  [anon_sym_EQ] = anon_sym_EQ,
  [aux_sym_number_literal_token1] = aux_sym_number_literal_token1,
  [anon_sym_0x] = anon_sym_0x,
  [aux_sym_number_literal_token2] = aux_sym_number_literal_token2,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_EQ_EQ_EQ] = anon_sym_EQ_EQ_EQ,
  [sym_identifier] = sym_identifier,
  [sym_string] = sym_string,
  [sym_line_comment] = sym_line_comment,
  [sym_block_comment] = sym_block_comment,
  [sym_source_file] = sym_source_file,
  [sym_header] = sym_header,
  [sym_package_declaration] = sym_package_declaration,
  [sym_uses_statement] = sym_uses_statement,
  [sym_qualified_identifier] = sym_qualified_identifier,
  [sym_statement] = sym_statement,
  [sym_function_declaration] = sym_function_declaration,
  [sym_parameter_list] = sym_parameter_list,
  [sym_block] = sym_block,
  [sym_variable_declaration] = sym_variable_declaration,
  [sym_variable_declarator_list] = sym_variable_declarator_list,
  [sym_variable_declarator] = sym_variable_declarator,
  [sym_variable_initializer] = sym_variable_initializer,
  [sym_array_initializer] = sym_array_initializer,
  [sym_expression_statement] = sym_expression_statement,
  [sym_expression] = sym_expression,
  [sym_number_literal] = sym_number_literal,
  [sym_binary_expression] = sym_binary_expression,
  [sym_function_call] = sym_function_call,
  [sym_argument_list] = sym_argument_list,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_source_file_repeat2] = aux_sym_source_file_repeat2,
  [aux_sym_header_repeat1] = aux_sym_header_repeat1,
  [aux_sym_qualified_identifier_repeat1] = aux_sym_qualified_identifier_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [aux_sym_variable_declarator_list_repeat1] = aux_sym_variable_declarator_list_repeat1,
  [aux_sym_array_initializer_repeat1] = aux_sym_array_initializer_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_package] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_uses] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_function] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_var] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_number_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_0x] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_number_literal_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_header] = {
    .visible = true,
    .named = true,
  },
  [sym_package_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_uses_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_qualified_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_function_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_declarator_list] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_declarator] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_initializer] = {
    .visible = true,
    .named = true,
  },
  [sym_array_initializer] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_number_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_header_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_qualified_identifier_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_variable_declarator_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_initializer_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 2,
  [12] = 12,
  [13] = 4,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 12,
  [18] = 18,
  [19] = 9,
  [20] = 10,
  [21] = 21,
  [22] = 5,
  [23] = 21,
  [24] = 16,
  [25] = 6,
  [26] = 7,
  [27] = 14,
  [28] = 8,
  [29] = 29,
  [30] = 30,
  [31] = 29,
  [32] = 30,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 33,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 41,
  [43] = 40,
  [44] = 44,
  [45] = 44,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 51,
  [53] = 53,
  [54] = 46,
  [55] = 47,
  [56] = 50,
  [57] = 48,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 64,
  [67] = 65,
  [68] = 58,
  [69] = 61,
  [70] = 63,
  [71] = 59,
  [72] = 62,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 73,
  [77] = 77,
  [78] = 75,
  [79] = 74,
  [80] = 77,
  [81] = 81,
  [82] = 82,
  [83] = 82,
  [84] = 81,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 87,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 86,
  [96] = 96,
  [97] = 92,
  [98] = 98,
  [99] = 98,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 102,
  [106] = 106,
  [107] = 107,
  [108] = 103,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 109,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 111,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(15);
      ADVANCE_MAP(
        '"', 2,
        '%', 38,
        '(', 21,
        ')', 23,
        '*', 36,
        '+', 34,
        ',', 22,
        '-', 35,
        '.', 19,
        '/', 37,
        '0', 31,
        ';', 17,
        '=', 28,
        'f', 58,
        'p', 41,
        'u', 55,
        'v', 42,
        '{', 24,
        '}', 25,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(29);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == ')') ADVANCE(23);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '0') ADVANCE(31);
      if (lookahead == '{') ADVANCE(24);
      if (lookahead == '}') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(29);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(60);
      if (lookahead == '\\') ADVANCE(11);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(61);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(62);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(33);
      END_STATE();
    case 7:
      if (lookahead == '=') ADVANCE(39);
      END_STATE();
    case 8:
      if (lookahead == '_') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 9:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(33);
      END_STATE();
    case 11:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 12:
      if (eof) ADVANCE(15);
      ADVANCE_MAP(
        '"', 2,
        '%', 38,
        '(', 21,
        ')', 23,
        '*', 36,
        '+', 34,
        ',', 22,
        '-', 35,
        '/', 37,
        '0', 31,
        ';', 17,
        '=', 7,
        'f', 58,
        'v', 42,
        '}', 25,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(12);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(29);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 13:
      if (eof) ADVANCE(15);
      ADVANCE_MAP(
        '"', 2,
        '%', 38,
        ')', 23,
        '*', 36,
        '+', 34,
        ',', 22,
        '-', 35,
        '/', 37,
        '0', 31,
        '=', 7,
        'f', 58,
        'p', 41,
        'v', 42,
        '}', 25,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(13);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(29);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 14:
      if (eof) ADVANCE(15);
      ADVANCE_MAP(
        '"', 2,
        ',', 22,
        '/', 3,
        '0', 31,
        '=', 27,
        'f', 58,
        'v', 42,
        '}', 25,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(14);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(29);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_package);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_uses);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_function);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_var);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(39);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_number_literal_token1);
      if (lookahead == '_') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_number_literal_token1);
      if (lookahead == '_') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_number_literal_token1);
      if (lookahead == 'x') ADVANCE(32);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_0x);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_number_literal_token2);
      if (lookahead == '_') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(61);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      if (lookahead == '=') ADVANCE(40);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_EQ_EQ_EQ);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'k') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_block_comment);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 13},
  [2] = {.lex_state = 12},
  [3] = {.lex_state = 13},
  [4] = {.lex_state = 12},
  [5] = {.lex_state = 12},
  [6] = {.lex_state = 12},
  [7] = {.lex_state = 12},
  [8] = {.lex_state = 12},
  [9] = {.lex_state = 12},
  [10] = {.lex_state = 12},
  [11] = {.lex_state = 12},
  [12] = {.lex_state = 12},
  [13] = {.lex_state = 12},
  [14] = {.lex_state = 12},
  [15] = {.lex_state = 12},
  [16] = {.lex_state = 12},
  [17] = {.lex_state = 12},
  [18] = {.lex_state = 12},
  [19] = {.lex_state = 12},
  [20] = {.lex_state = 12},
  [21] = {.lex_state = 12},
  [22] = {.lex_state = 12},
  [23] = {.lex_state = 12},
  [24] = {.lex_state = 12},
  [25] = {.lex_state = 12},
  [26] = {.lex_state = 12},
  [27] = {.lex_state = 12},
  [28] = {.lex_state = 12},
  [29] = {.lex_state = 12},
  [30] = {.lex_state = 12},
  [31] = {.lex_state = 12},
  [32] = {.lex_state = 12},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 13},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 13},
  [40] = {.lex_state = 13},
  [41] = {.lex_state = 13},
  [42] = {.lex_state = 13},
  [43] = {.lex_state = 13},
  [44] = {.lex_state = 14},
  [45] = {.lex_state = 14},
  [46] = {.lex_state = 12},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 12},
  [51] = {.lex_state = 12},
  [52] = {.lex_state = 12},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 12},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 12},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 12},
  [59] = {.lex_state = 12},
  [60] = {.lex_state = 1},
  [61] = {.lex_state = 12},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 12},
  [64] = {.lex_state = 12},
  [65] = {.lex_state = 12},
  [66] = {.lex_state = 12},
  [67] = {.lex_state = 12},
  [68] = {.lex_state = 12},
  [69] = {.lex_state = 12},
  [70] = {.lex_state = 12},
  [71] = {.lex_state = 12},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 12},
  [74] = {.lex_state = 12},
  [75] = {.lex_state = 12},
  [76] = {.lex_state = 12},
  [77] = {.lex_state = 12},
  [78] = {.lex_state = 12},
  [79] = {.lex_state = 12},
  [80] = {.lex_state = 12},
  [81] = {.lex_state = 12},
  [82] = {.lex_state = 12},
  [83] = {.lex_state = 12},
  [84] = {.lex_state = 12},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 1},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 1},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 1},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 1},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 1},
  [105] = {.lex_state = 1},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 1},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 6},
  [110] = {.lex_state = 1},
  [111] = {.lex_state = 1},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 6},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 1},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_package] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_uses] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_function] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_var] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [aux_sym_number_literal_token1] = ACTIONS(1),
    [anon_sym_0x] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(115),
    [sym_header] = STATE(3),
    [sym_package_declaration] = STATE(34),
    [sym_statement] = STATE(15),
    [sym_function_declaration] = STATE(75),
    [sym_variable_declaration] = STATE(75),
    [sym_expression_statement] = STATE(75),
    [sym_expression] = STATE(29),
    [sym_number_literal] = STATE(9),
    [sym_binary_expression] = STATE(9),
    [sym_function_call] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_source_file_repeat2] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_package] = ACTIONS(7),
    [anon_sym_function] = ACTIONS(9),
    [anon_sym_var] = ACTIONS(11),
    [aux_sym_number_literal_token1] = ACTIONS(13),
    [anon_sym_0x] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
    [sym_string] = ACTIONS(19),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    STATE(5), 1,
      sym_argument_list,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(23), 6,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      sym_identifier,
    ACTIONS(21), 12,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
      sym_string,
  [33] = 15,
    ACTIONS(7), 1,
      anon_sym_package,
    ACTIONS(9), 1,
      anon_sym_function,
    ACTIONS(11), 1,
      anon_sym_var,
    ACTIONS(13), 1,
      aux_sym_number_literal_token1,
    ACTIONS(15), 1,
      anon_sym_0x,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(19), 1,
      sym_string,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    STATE(29), 1,
      sym_expression,
    STATE(34), 1,
      sym_package_declaration,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(18), 2,
      sym_statement,
      aux_sym_source_file_repeat2,
    STATE(37), 2,
      sym_header,
      aux_sym_source_file_repeat1,
    STATE(9), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
    STATE(75), 3,
      sym_function_declaration,
      sym_variable_declaration,
      sym_expression_statement,
  [86] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(31), 6,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      sym_identifier,
    ACTIONS(29), 12,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
      sym_string,
  [113] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(35), 6,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      sym_identifier,
    ACTIONS(33), 12,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
      sym_string,
  [140] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(39), 6,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      sym_identifier,
    ACTIONS(37), 12,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
      sym_string,
  [167] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(43), 6,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      sym_identifier,
    ACTIONS(41), 12,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
      sym_string,
  [194] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(47), 6,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      sym_identifier,
    ACTIONS(45), 12,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
      sym_string,
  [221] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(23), 6,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      sym_identifier,
    ACTIONS(21), 12,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
      sym_string,
  [248] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(51), 6,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      sym_identifier,
    ACTIONS(49), 12,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
      sym_string,
  [275] = 5,
    ACTIONS(53), 1,
      anon_sym_LPAREN,
    STATE(22), 1,
      sym_argument_list,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(23), 6,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      sym_identifier,
    ACTIONS(21), 10,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
      sym_string,
  [306] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(57), 6,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      sym_identifier,
    ACTIONS(55), 12,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
      sym_string,
  [333] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(31), 6,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      sym_identifier,
    ACTIONS(29), 10,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
      sym_string,
  [358] = 12,
    ACTIONS(59), 1,
      anon_sym_function,
    ACTIONS(61), 1,
      anon_sym_RBRACE,
    ACTIONS(63), 1,
      anon_sym_var,
    ACTIONS(65), 1,
      aux_sym_number_literal_token1,
    ACTIONS(67), 1,
      anon_sym_0x,
    ACTIONS(69), 1,
      sym_identifier,
    ACTIONS(71), 1,
      sym_string,
    STATE(31), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(23), 2,
      sym_statement,
      aux_sym_source_file_repeat2,
    STATE(19), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
    STATE(78), 3,
      sym_function_declaration,
      sym_variable_declaration,
      sym_expression_statement,
  [401] = 12,
    ACTIONS(9), 1,
      anon_sym_function,
    ACTIONS(11), 1,
      anon_sym_var,
    ACTIONS(13), 1,
      aux_sym_number_literal_token1,
    ACTIONS(15), 1,
      anon_sym_0x,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(19), 1,
      sym_string,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    STATE(29), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(21), 2,
      sym_statement,
      aux_sym_source_file_repeat2,
    STATE(9), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
    STATE(75), 3,
      sym_function_declaration,
      sym_variable_declaration,
      sym_expression_statement,
  [444] = 12,
    ACTIONS(59), 1,
      anon_sym_function,
    ACTIONS(63), 1,
      anon_sym_var,
    ACTIONS(65), 1,
      aux_sym_number_literal_token1,
    ACTIONS(67), 1,
      anon_sym_0x,
    ACTIONS(69), 1,
      sym_identifier,
    ACTIONS(71), 1,
      sym_string,
    ACTIONS(73), 1,
      anon_sym_RBRACE,
    STATE(31), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(14), 2,
      sym_statement,
      aux_sym_source_file_repeat2,
    STATE(19), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
    STATE(78), 3,
      sym_function_declaration,
      sym_variable_declaration,
      sym_expression_statement,
  [487] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(57), 6,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      sym_identifier,
    ACTIONS(55), 10,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
      sym_string,
  [512] = 12,
    ACTIONS(9), 1,
      anon_sym_function,
    ACTIONS(11), 1,
      anon_sym_var,
    ACTIONS(13), 1,
      aux_sym_number_literal_token1,
    ACTIONS(15), 1,
      anon_sym_0x,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(19), 1,
      sym_string,
    ACTIONS(75), 1,
      ts_builtin_sym_end,
    STATE(29), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(21), 2,
      sym_statement,
      aux_sym_source_file_repeat2,
    STATE(9), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
    STATE(75), 3,
      sym_function_declaration,
      sym_variable_declaration,
      sym_expression_statement,
  [555] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(23), 6,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      sym_identifier,
    ACTIONS(21), 10,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
      sym_string,
  [580] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(51), 6,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      sym_identifier,
    ACTIONS(49), 10,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
      sym_string,
  [605] = 12,
    ACTIONS(77), 1,
      ts_builtin_sym_end,
    ACTIONS(79), 1,
      anon_sym_function,
    ACTIONS(82), 1,
      anon_sym_var,
    ACTIONS(85), 1,
      aux_sym_number_literal_token1,
    ACTIONS(88), 1,
      anon_sym_0x,
    ACTIONS(91), 1,
      sym_identifier,
    ACTIONS(94), 1,
      sym_string,
    STATE(29), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(21), 2,
      sym_statement,
      aux_sym_source_file_repeat2,
    STATE(9), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
    STATE(75), 3,
      sym_function_declaration,
      sym_variable_declaration,
      sym_expression_statement,
  [648] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(35), 6,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      sym_identifier,
    ACTIONS(33), 10,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
      sym_string,
  [673] = 12,
    ACTIONS(77), 1,
      anon_sym_RBRACE,
    ACTIONS(97), 1,
      anon_sym_function,
    ACTIONS(100), 1,
      anon_sym_var,
    ACTIONS(103), 1,
      aux_sym_number_literal_token1,
    ACTIONS(106), 1,
      anon_sym_0x,
    ACTIONS(109), 1,
      sym_identifier,
    ACTIONS(112), 1,
      sym_string,
    STATE(31), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(23), 2,
      sym_statement,
      aux_sym_source_file_repeat2,
    STATE(19), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
    STATE(78), 3,
      sym_function_declaration,
      sym_variable_declaration,
      sym_expression_statement,
  [716] = 12,
    ACTIONS(59), 1,
      anon_sym_function,
    ACTIONS(63), 1,
      anon_sym_var,
    ACTIONS(65), 1,
      aux_sym_number_literal_token1,
    ACTIONS(67), 1,
      anon_sym_0x,
    ACTIONS(69), 1,
      sym_identifier,
    ACTIONS(71), 1,
      sym_string,
    ACTIONS(115), 1,
      anon_sym_RBRACE,
    STATE(31), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(27), 2,
      sym_statement,
      aux_sym_source_file_repeat2,
    STATE(19), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
    STATE(78), 3,
      sym_function_declaration,
      sym_variable_declaration,
      sym_expression_statement,
  [759] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(39), 6,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      sym_identifier,
    ACTIONS(37), 10,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
      sym_string,
  [784] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(43), 6,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      sym_identifier,
    ACTIONS(41), 10,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
      sym_string,
  [809] = 12,
    ACTIONS(59), 1,
      anon_sym_function,
    ACTIONS(63), 1,
      anon_sym_var,
    ACTIONS(65), 1,
      aux_sym_number_literal_token1,
    ACTIONS(67), 1,
      anon_sym_0x,
    ACTIONS(69), 1,
      sym_identifier,
    ACTIONS(71), 1,
      sym_string,
    ACTIONS(117), 1,
      anon_sym_RBRACE,
    STATE(31), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(23), 2,
      sym_statement,
      aux_sym_source_file_repeat2,
    STATE(19), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
    STATE(78), 3,
      sym_function_declaration,
      sym_variable_declaration,
      sym_expression_statement,
  [852] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(47), 6,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      sym_identifier,
    ACTIONS(45), 10,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
      sym_string,
  [877] = 6,
    ACTIONS(121), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(127), 2,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
    ACTIONS(119), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    ACTIONS(123), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
    ACTIONS(125), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
  [907] = 5,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(127), 2,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
    ACTIONS(129), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_0x,
      sym_string,
    ACTIONS(131), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
    ACTIONS(125), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
  [935] = 6,
    ACTIONS(133), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(137), 2,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
    ACTIONS(119), 3,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
    ACTIONS(123), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
    ACTIONS(135), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
  [965] = 5,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(137), 2,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
    ACTIONS(129), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
    ACTIONS(131), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
    ACTIONS(135), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
  [993] = 10,
    ACTIONS(13), 1,
      aux_sym_number_literal_token1,
    ACTIONS(15), 1,
      anon_sym_0x,
    ACTIONS(19), 1,
      sym_string,
    ACTIONS(139), 1,
      anon_sym_LBRACE,
    ACTIONS(141), 1,
      sym_identifier,
    STATE(30), 1,
      sym_expression,
    STATE(64), 1,
      sym_variable_initializer,
    STATE(65), 1,
      sym_array_initializer,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(9), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
  [1027] = 5,
    ACTIONS(147), 1,
      anon_sym_uses,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(36), 2,
      sym_uses_statement,
      aux_sym_header_repeat1,
    ACTIONS(143), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    ACTIONS(145), 5,
      anon_sym_package,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1051] = 5,
    ACTIONS(153), 1,
      anon_sym_uses,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(35), 2,
      sym_uses_statement,
      aux_sym_header_repeat1,
    ACTIONS(149), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    ACTIONS(151), 5,
      anon_sym_package,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1075] = 5,
    ACTIONS(147), 1,
      anon_sym_uses,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(35), 2,
      sym_uses_statement,
      aux_sym_header_repeat1,
    ACTIONS(156), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    ACTIONS(158), 5,
      anon_sym_package,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1099] = 6,
    ACTIONS(162), 1,
      anon_sym_package,
    STATE(34), 1,
      sym_package_declaration,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(37), 2,
      sym_header,
      aux_sym_source_file_repeat1,
    ACTIONS(160), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    ACTIONS(165), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1125] = 10,
    ACTIONS(65), 1,
      aux_sym_number_literal_token1,
    ACTIONS(67), 1,
      anon_sym_0x,
    ACTIONS(71), 1,
      sym_string,
    ACTIONS(167), 1,
      anon_sym_LBRACE,
    ACTIONS(169), 1,
      sym_identifier,
    STATE(32), 1,
      sym_expression,
    STATE(66), 1,
      sym_variable_initializer,
    STATE(67), 1,
      sym_array_initializer,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(19), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
  [1159] = 4,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(127), 2,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
    ACTIONS(171), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
    ACTIONS(125), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
  [1180] = 6,
    ACTIONS(173), 1,
      anon_sym_COMMA,
    ACTIONS(175), 1,
      anon_sym_RPAREN,
    STATE(95), 1,
      aux_sym_array_initializer_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(127), 2,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
    ACTIONS(125), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
  [1205] = 6,
    ACTIONS(173), 1,
      anon_sym_COMMA,
    ACTIONS(177), 1,
      anon_sym_RBRACE,
    STATE(92), 1,
      aux_sym_array_initializer_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(127), 2,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
    ACTIONS(125), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
  [1230] = 6,
    ACTIONS(173), 1,
      anon_sym_COMMA,
    ACTIONS(179), 1,
      anon_sym_RBRACE,
    STATE(97), 1,
      aux_sym_array_initializer_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(127), 2,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
    ACTIONS(125), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
  [1255] = 6,
    ACTIONS(173), 1,
      anon_sym_COMMA,
    ACTIONS(181), 1,
      anon_sym_RPAREN,
    STATE(86), 1,
      aux_sym_array_initializer_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(127), 2,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
    ACTIONS(125), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ_EQ,
  [1280] = 4,
    ACTIONS(187), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(183), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
    ACTIONS(185), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
  [1300] = 4,
    ACTIONS(189), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(183), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
    ACTIONS(185), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_0x,
      sym_string,
  [1320] = 5,
    ACTIONS(195), 1,
      anon_sym_COMMA,
    STATE(46), 1,
      aux_sym_variable_declarator_list_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(191), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    ACTIONS(193), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1342] = 8,
    ACTIONS(13), 1,
      aux_sym_number_literal_token1,
    ACTIONS(15), 1,
      anon_sym_0x,
    ACTIONS(19), 1,
      sym_string,
    ACTIONS(141), 1,
      sym_identifier,
    ACTIONS(198), 1,
      anon_sym_RPAREN,
    STATE(43), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(9), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
  [1370] = 8,
    ACTIONS(13), 1,
      aux_sym_number_literal_token1,
    ACTIONS(15), 1,
      anon_sym_0x,
    ACTIONS(19), 1,
      sym_string,
    ACTIONS(141), 1,
      sym_identifier,
    ACTIONS(200), 1,
      anon_sym_RBRACE,
    STATE(41), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(9), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
  [1398] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(202), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    ACTIONS(204), 6,
      anon_sym_package,
      anon_sym_uses,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1416] = 5,
    ACTIONS(208), 1,
      anon_sym_COMMA,
    STATE(52), 1,
      aux_sym_variable_declarator_list_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(210), 3,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
    ACTIONS(206), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1438] = 5,
    ACTIONS(216), 1,
      anon_sym_COMMA,
    STATE(46), 1,
      aux_sym_variable_declarator_list_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(212), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    ACTIONS(214), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1460] = 5,
    ACTIONS(208), 1,
      anon_sym_COMMA,
    STATE(54), 1,
      aux_sym_variable_declarator_list_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(212), 3,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
    ACTIONS(214), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1482] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(218), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    ACTIONS(220), 6,
      anon_sym_package,
      anon_sym_uses,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1500] = 5,
    ACTIONS(222), 1,
      anon_sym_COMMA,
    STATE(54), 1,
      aux_sym_variable_declarator_list_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(191), 3,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
    ACTIONS(193), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1522] = 8,
    ACTIONS(13), 1,
      aux_sym_number_literal_token1,
    ACTIONS(15), 1,
      anon_sym_0x,
    ACTIONS(19), 1,
      sym_string,
    ACTIONS(141), 1,
      sym_identifier,
    ACTIONS(225), 1,
      anon_sym_RPAREN,
    STATE(40), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(9), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
  [1550] = 5,
    ACTIONS(216), 1,
      anon_sym_COMMA,
    STATE(51), 1,
      aux_sym_variable_declarator_list_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(210), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    ACTIONS(206), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1572] = 8,
    ACTIONS(13), 1,
      aux_sym_number_literal_token1,
    ACTIONS(15), 1,
      anon_sym_0x,
    ACTIONS(19), 1,
      sym_string,
    ACTIONS(141), 1,
      sym_identifier,
    ACTIONS(227), 1,
      anon_sym_RBRACE,
    STATE(42), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(9), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
  [1600] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(229), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_0x,
      sym_string,
    ACTIONS(231), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1617] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(191), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_0x,
      sym_string,
    ACTIONS(193), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1634] = 7,
    ACTIONS(13), 1,
      aux_sym_number_literal_token1,
    ACTIONS(15), 1,
      anon_sym_0x,
    ACTIONS(19), 1,
      sym_string,
    ACTIONS(141), 1,
      sym_identifier,
    STATE(39), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(9), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
  [1659] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(233), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_0x,
      sym_string,
    ACTIONS(235), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1676] = 7,
    ACTIONS(13), 1,
      aux_sym_number_literal_token1,
    ACTIONS(15), 1,
      anon_sym_0x,
    ACTIONS(19), 1,
      sym_string,
    ACTIONS(141), 1,
      sym_identifier,
    STATE(7), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(9), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
  [1701] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(237), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_0x,
      sym_string,
    ACTIONS(239), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1718] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(241), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_0x,
      sym_string,
    ACTIONS(243), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1735] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(129), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_0x,
      sym_string,
    ACTIONS(131), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1752] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(241), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
    ACTIONS(243), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1769] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(129), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
    ACTIONS(131), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1786] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(229), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
    ACTIONS(231), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1803] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(233), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
    ACTIONS(235), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1820] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(237), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
    ACTIONS(239), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1837] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(191), 4,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
    ACTIONS(193), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1854] = 7,
    ACTIONS(65), 1,
      aux_sym_number_literal_token1,
    ACTIONS(67), 1,
      anon_sym_0x,
    ACTIONS(71), 1,
      sym_string,
    ACTIONS(169), 1,
      sym_identifier,
    STATE(26), 1,
      sym_expression,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(19), 3,
      sym_number_literal,
      sym_binary_expression,
      sym_function_call,
  [1879] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(247), 3,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
    ACTIONS(245), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1895] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(249), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    ACTIONS(251), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1911] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(253), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    ACTIONS(255), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1927] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(247), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    ACTIONS(245), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1943] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(257), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    ACTIONS(259), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1959] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(253), 3,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
    ACTIONS(255), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1975] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(249), 3,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
    ACTIONS(251), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [1991] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(257), 3,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
    ACTIONS(259), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [2007] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(261), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    ACTIONS(263), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [2023] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(267), 3,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
    ACTIONS(265), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [2039] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(267), 3,
      ts_builtin_sym_end,
      anon_sym_0x,
      sym_string,
    ACTIONS(265), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [2055] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(261), 3,
      anon_sym_RBRACE,
      anon_sym_0x,
      sym_string,
    ACTIONS(263), 4,
      anon_sym_function,
      anon_sym_var,
      aux_sym_number_literal_token1,
      sym_identifier,
  [2071] = 4,
    ACTIONS(269), 1,
      anon_sym_COMMA,
    STATE(85), 1,
      aux_sym_array_initializer_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(171), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [2086] = 4,
    ACTIONS(173), 1,
      anon_sym_COMMA,
    ACTIONS(272), 1,
      anon_sym_RPAREN,
    STATE(85), 1,
      aux_sym_array_initializer_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2100] = 4,
    ACTIONS(274), 1,
      sym_identifier,
    STATE(56), 1,
      sym_variable_declarator,
    STATE(74), 1,
      sym_variable_declarator_list,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2114] = 4,
    ACTIONS(276), 1,
      anon_sym_SEMI,
    ACTIONS(278), 1,
      anon_sym_DOT,
    STATE(94), 1,
      aux_sym_qualified_identifier_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2128] = 4,
    ACTIONS(280), 1,
      anon_sym_COMMA,
    ACTIONS(282), 1,
      anon_sym_RPAREN,
    STATE(93), 1,
      aux_sym_parameter_list_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2142] = 4,
    ACTIONS(278), 1,
      anon_sym_DOT,
    ACTIONS(284), 1,
      anon_sym_SEMI,
    STATE(88), 1,
      aux_sym_qualified_identifier_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2156] = 4,
    ACTIONS(286), 1,
      sym_identifier,
    STATE(50), 1,
      sym_variable_declarator,
    STATE(79), 1,
      sym_variable_declarator_list,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2170] = 4,
    ACTIONS(173), 1,
      anon_sym_COMMA,
    ACTIONS(288), 1,
      anon_sym_RBRACE,
    STATE(85), 1,
      aux_sym_array_initializer_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2184] = 4,
    ACTIONS(290), 1,
      anon_sym_COMMA,
    ACTIONS(293), 1,
      anon_sym_RPAREN,
    STATE(93), 1,
      aux_sym_parameter_list_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2198] = 4,
    ACTIONS(295), 1,
      anon_sym_SEMI,
    ACTIONS(297), 1,
      anon_sym_DOT,
    STATE(94), 1,
      aux_sym_qualified_identifier_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2212] = 4,
    ACTIONS(173), 1,
      anon_sym_COMMA,
    ACTIONS(300), 1,
      anon_sym_RPAREN,
    STATE(85), 1,
      aux_sym_array_initializer_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2226] = 4,
    ACTIONS(280), 1,
      anon_sym_COMMA,
    ACTIONS(302), 1,
      anon_sym_RPAREN,
    STATE(89), 1,
      aux_sym_parameter_list_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2240] = 4,
    ACTIONS(173), 1,
      anon_sym_COMMA,
    ACTIONS(304), 1,
      anon_sym_RBRACE,
    STATE(85), 1,
      aux_sym_array_initializer_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2254] = 3,
    ACTIONS(306), 1,
      anon_sym_LBRACE,
    STATE(80), 1,
      sym_block,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2265] = 3,
    ACTIONS(308), 1,
      anon_sym_LBRACE,
    STATE(77), 1,
      sym_block,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2276] = 3,
    ACTIONS(310), 1,
      anon_sym_RPAREN,
    ACTIONS(312), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2287] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(293), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2296] = 3,
    ACTIONS(286), 1,
      sym_identifier,
    STATE(71), 1,
      sym_variable_declarator,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2307] = 3,
    ACTIONS(314), 1,
      anon_sym_LPAREN,
    STATE(99), 1,
      sym_parameter_list,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2318] = 3,
    ACTIONS(316), 1,
      sym_identifier,
    STATE(116), 1,
      sym_qualified_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2329] = 3,
    ACTIONS(274), 1,
      sym_identifier,
    STATE(59), 1,
      sym_variable_declarator,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2340] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(295), 2,
      anon_sym_SEMI,
      anon_sym_DOT,
  [2349] = 3,
    ACTIONS(316), 1,
      sym_identifier,
    STATE(119), 1,
      sym_qualified_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2360] = 3,
    ACTIONS(314), 1,
      anon_sym_LPAREN,
    STATE(98), 1,
      sym_parameter_list,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2371] = 2,
    ACTIONS(318), 1,
      aux_sym_number_literal_token2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2379] = 2,
    ACTIONS(320), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2387] = 2,
    ACTIONS(322), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2395] = 2,
    ACTIONS(324), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2403] = 2,
    ACTIONS(326), 1,
      aux_sym_number_literal_token2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2411] = 2,
    ACTIONS(328), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2419] = 2,
    ACTIONS(330), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2427] = 2,
    ACTIONS(332), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2435] = 2,
    ACTIONS(334), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2443] = 2,
    ACTIONS(336), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2451] = 2,
    ACTIONS(338), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [2459] = 2,
    ACTIONS(340), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 33,
  [SMALL_STATE(4)] = 86,
  [SMALL_STATE(5)] = 113,
  [SMALL_STATE(6)] = 140,
  [SMALL_STATE(7)] = 167,
  [SMALL_STATE(8)] = 194,
  [SMALL_STATE(9)] = 221,
  [SMALL_STATE(10)] = 248,
  [SMALL_STATE(11)] = 275,
  [SMALL_STATE(12)] = 306,
  [SMALL_STATE(13)] = 333,
  [SMALL_STATE(14)] = 358,
  [SMALL_STATE(15)] = 401,
  [SMALL_STATE(16)] = 444,
  [SMALL_STATE(17)] = 487,
  [SMALL_STATE(18)] = 512,
  [SMALL_STATE(19)] = 555,
  [SMALL_STATE(20)] = 580,
  [SMALL_STATE(21)] = 605,
  [SMALL_STATE(22)] = 648,
  [SMALL_STATE(23)] = 673,
  [SMALL_STATE(24)] = 716,
  [SMALL_STATE(25)] = 759,
  [SMALL_STATE(26)] = 784,
  [SMALL_STATE(27)] = 809,
  [SMALL_STATE(28)] = 852,
  [SMALL_STATE(29)] = 877,
  [SMALL_STATE(30)] = 907,
  [SMALL_STATE(31)] = 935,
  [SMALL_STATE(32)] = 965,
  [SMALL_STATE(33)] = 993,
  [SMALL_STATE(34)] = 1027,
  [SMALL_STATE(35)] = 1051,
  [SMALL_STATE(36)] = 1075,
  [SMALL_STATE(37)] = 1099,
  [SMALL_STATE(38)] = 1125,
  [SMALL_STATE(39)] = 1159,
  [SMALL_STATE(40)] = 1180,
  [SMALL_STATE(41)] = 1205,
  [SMALL_STATE(42)] = 1230,
  [SMALL_STATE(43)] = 1255,
  [SMALL_STATE(44)] = 1280,
  [SMALL_STATE(45)] = 1300,
  [SMALL_STATE(46)] = 1320,
  [SMALL_STATE(47)] = 1342,
  [SMALL_STATE(48)] = 1370,
  [SMALL_STATE(49)] = 1398,
  [SMALL_STATE(50)] = 1416,
  [SMALL_STATE(51)] = 1438,
  [SMALL_STATE(52)] = 1460,
  [SMALL_STATE(53)] = 1482,
  [SMALL_STATE(54)] = 1500,
  [SMALL_STATE(55)] = 1522,
  [SMALL_STATE(56)] = 1550,
  [SMALL_STATE(57)] = 1572,
  [SMALL_STATE(58)] = 1600,
  [SMALL_STATE(59)] = 1617,
  [SMALL_STATE(60)] = 1634,
  [SMALL_STATE(61)] = 1659,
  [SMALL_STATE(62)] = 1676,
  [SMALL_STATE(63)] = 1701,
  [SMALL_STATE(64)] = 1718,
  [SMALL_STATE(65)] = 1735,
  [SMALL_STATE(66)] = 1752,
  [SMALL_STATE(67)] = 1769,
  [SMALL_STATE(68)] = 1786,
  [SMALL_STATE(69)] = 1803,
  [SMALL_STATE(70)] = 1820,
  [SMALL_STATE(71)] = 1837,
  [SMALL_STATE(72)] = 1854,
  [SMALL_STATE(73)] = 1879,
  [SMALL_STATE(74)] = 1895,
  [SMALL_STATE(75)] = 1911,
  [SMALL_STATE(76)] = 1927,
  [SMALL_STATE(77)] = 1943,
  [SMALL_STATE(78)] = 1959,
  [SMALL_STATE(79)] = 1975,
  [SMALL_STATE(80)] = 1991,
  [SMALL_STATE(81)] = 2007,
  [SMALL_STATE(82)] = 2023,
  [SMALL_STATE(83)] = 2039,
  [SMALL_STATE(84)] = 2055,
  [SMALL_STATE(85)] = 2071,
  [SMALL_STATE(86)] = 2086,
  [SMALL_STATE(87)] = 2100,
  [SMALL_STATE(88)] = 2114,
  [SMALL_STATE(89)] = 2128,
  [SMALL_STATE(90)] = 2142,
  [SMALL_STATE(91)] = 2156,
  [SMALL_STATE(92)] = 2170,
  [SMALL_STATE(93)] = 2184,
  [SMALL_STATE(94)] = 2198,
  [SMALL_STATE(95)] = 2212,
  [SMALL_STATE(96)] = 2226,
  [SMALL_STATE(97)] = 2240,
  [SMALL_STATE(98)] = 2254,
  [SMALL_STATE(99)] = 2265,
  [SMALL_STATE(100)] = 2276,
  [SMALL_STATE(101)] = 2287,
  [SMALL_STATE(102)] = 2296,
  [SMALL_STATE(103)] = 2307,
  [SMALL_STATE(104)] = 2318,
  [SMALL_STATE(105)] = 2329,
  [SMALL_STATE(106)] = 2340,
  [SMALL_STATE(107)] = 2349,
  [SMALL_STATE(108)] = 2360,
  [SMALL_STATE(109)] = 2371,
  [SMALL_STATE(110)] = 2379,
  [SMALL_STATE(111)] = 2387,
  [SMALL_STATE(112)] = 2395,
  [SMALL_STATE(113)] = 2403,
  [SMALL_STATE(114)] = 2411,
  [SMALL_STATE(115)] = 2419,
  [SMALL_STATE(116)] = 2427,
  [SMALL_STATE(117)] = 2435,
  [SMALL_STATE(118)] = 2443,
  [SMALL_STATE(119)] = 2451,
  [SMALL_STATE(120)] = 2459,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(104),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(111),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number_literal, 2, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number_literal, 2, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 2, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 2, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 2, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 2, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 3, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 3, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 4, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument_list, 4, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number_literal, 1, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number_literal, 1, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(120),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0),
  [79] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(111),
  [82] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(87),
  [85] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(12),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(113),
  [91] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(2),
  [94] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(9),
  [97] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(120),
  [100] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(91),
  [103] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(17),
  [106] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(109),
  [109] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(11),
  [112] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(19),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_statement, 1, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_statement, 1, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [127] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_initializer, 1, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_initializer, 1, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [137] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 1, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header, 1, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = false}}, SHIFT(107),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_header_repeat1, 2, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_header_repeat1, 2, 0, 0),
  [153] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_header_repeat1, 2, 0, 0), SHIFT_REPEAT(107),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 2, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header, 2, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [162] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(104),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_initializer_repeat1, 2, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declarator, 1, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declarator, 1, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_variable_declarator_list_repeat1, 2, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_variable_declarator_list_repeat1, 2, 0, 0),
  [195] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_variable_declarator_list_repeat1, 2, 0, 0), SHIFT_REPEAT(105),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_uses_statement, 3, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_uses_statement, 3, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declarator_list, 1, 0, 0),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declarator_list, 1, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declarator_list, 2, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declarator_list, 2, 0, 0),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_package_declaration, 3, 0, 0),
  [220] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_package_declaration, 3, 0, 0),
  [222] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_variable_declarator_list_repeat1, 2, 0, 0), SHIFT_REPEAT(102),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_initializer, 2, 0, 0),
  [231] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_initializer, 2, 0, 0),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_initializer, 4, 0, 0),
  [235] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_initializer, 4, 0, 0),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_initializer, 3, 0, 0),
  [239] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_initializer, 3, 0, 0),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declarator, 3, 0, 0),
  [243] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declarator, 3, 0, 0),
  [245] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_statement, 2, 0, 0),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_statement, 2, 0, 0),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declaration, 2, 0, 0),
  [251] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 2, 0, 0),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [255] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1, 0, 0),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_declaration, 4, 0, 0),
  [259] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_declaration, 4, 0, 0),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [263] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [265] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [269] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_initializer_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_qualified_identifier, 2, 0, 0),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [284] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_qualified_identifier, 1, 0, 0),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [290] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0), SHIFT_REPEAT(118),
  [293] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_qualified_identifier_repeat1, 2, 0, 0),
  [297] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_qualified_identifier_repeat1, 2, 0, 0), SHIFT_REPEAT(110),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [324] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 4, 0, 0),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [328] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 3, 0, 0),
  [330] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [334] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2, 0, 0),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_gosu(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
